Repository globus/globus-compute, pull requests merged in 2022-07, with the labels that each got.

#840 Docs fixes
  changelog.d/20220705_163242_chris_funcx_client_url_mismatch.rst
  changelog.d/20220706_095230_LeiGlobus_off_process_checker_removal_sc_13659.rst
  docs/actionprovider.rst
  docs/changelog.rst
  docs/configuring.rst
  docs/debugging.rst
  docs/endpoints.rst
  docs/executor.rst
  docs/sdk.rst
Labels: no-news-is-good-news

#841 Mild set of changes to appease mypy
  funcx_endpoint/funcx_endpoint/executors/high_throughput/executor.py
Labels: no-news-is-good-news, quick-review

#842 Mild status loop refactor
  funcx_endpoint/funcx_endpoint/executors/high_throughput/funcx_manager.py
Labels: no-news-is-good-news, quick-review

#843 Minor loop refactor
  funcx_endpoint/funcx_endpoint/executors/high_throughput/executor.py
Labels: no-news-is-good-news, quick-review

#838 Add tblib python dependency
  funcx_sdk/setup.py
Labels: no-news-is-good-news

#848 Publishing a message is probably not an emergency
  funcx_endpoint/funcx_endpoint/endpoint/interchange.py
Labels: no-news-is-good-news

#846 Lower severity of task submission warning
  funcx_endpoint/funcx_endpoint/endpoint/interchange.py
Labels: no-news-is-good-news

#850 Move error handling code, use for task cancel
  funcx_endpoint/funcx_endpoint/exception_handling.py
  funcx_endpoint/funcx_endpoint/exceptions.py
  funcx_endpoint/funcx_endpoint/executors/high_throughput/funcx_manager.py
  funcx_endpoint/funcx_endpoint/executors/high_throughput/funcx_worker.py
Labels: no-news-is-good-news

#851 Teach endpoint new Task state data structure
  changelog.d/20220715_160834_kevin_update_status_delta_per_fx_common_change.rst
  funcx_endpoint/funcx_endpoint/executors/high_throughput/funcx_manager.py
  funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
  funcx_endpoint/tests/unit/test_funcx_manager_unit.py
  funcx_endpoint/tests/unit/test_highthroughputinterchange.py
Labels: quick-review

#854 No sense in repeating unchanging information
  funcx_endpoint/funcx_endpoint/strategies/simple.py
Labels: no-news-is-good-news, quick-review

#847 Remove typoed manual thread annotation in favour of existing automatic log annotation
  funcx_endpoint/funcx_endpoint/endpoint/interchange.py
Labels: no-news-is-good-news

#858 Log which manager a task was sent to
  funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
Labels: no-news-is-good-news

#857 Reduce severity of endpoint message appearing multiple times per second
  funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange_task_dispatch.py
Labels: no-news-is-good-news

#856 Report task ID, not repr(), in received task message
  funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
Labels: no-news-is-good-news

#861 Remove unnecessary log statement.
  funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
Labels: no-news-is-good-news, quick-review

#863 Correct smoke test slack notification condition
  .github/_support/github-slack-notify.py
Labels: no-news-is-good-news
