Repository globus/globus-compute, pull requests merged in 2022-11, with the labels that each got.

#952 Correct link to client login description
  docs/endpoints.rst
  docs/sdk.rst
Labels: bug, Documentation, no-news-is-good-news

#953 Bump versions and changelog for (alpha) release
  changelog.d/20220930_151519_kevin_batch_add_interface_cleanup.rst
  changelog.d/20221015_134646_kevin_refactor_executor_constructor_signature.rst
  changelog.d/20221028_065929_rchard_ati_with_htex_fix.rst
  docs/changelog.rst
  funcx_endpoint/funcx_endpoint/version.py
  funcx_sdk/funcx/version.py
Labels: no-news-is-good-news, quick-review

#955 Remove monkeypatching of sqlite adapter
  changelog.d/20221106_000523_kevin_remove_monkeypatch.rst
  funcx_sdk/funcx/sdk/login_manager/tokenstore.py
  funcx_sdk/setup.py
Labels: quick-review

#957 Add .reload_tasks() to executor smoke test
  smoke_tests/tests/test_running_functions.py
Labels: no-news-is-good-news, quick-review

#961 Mypy got more strict this weekend
  funcx_sdk/funcx/sdk/asynchronous/ws_polling_task.py
  funcx_sdk/funcx/sdk/batch.py
  funcx_sdk/funcx/sdk/executor.py
Labels: no-news-is-good-news, quick-review

#958 Enable smoke tests against a LOCAL setup
  smoke_tests/Makefile
  smoke_tests/README.md
  smoke_tests/tests/conftest.py
  smoke_tests/tox.ini
Labels: no-news-is-good-news, quick-review

#959 Adding a doc entry and example config for accelerator pinning.
  docs/configs/worker_pinning.py
  docs/configuring.rst
Labels: no-news-is-good-news

#960 Make the tests directory a Python package
  funcx_sdk/tests/__init__.py
Labels: no-news-is-good-news

#963 Turn endpoint status test back on
  smoke_tests/tests/test_s3_indirect.py
  smoke_tests/tests/test_version.py
Labels: no-news-is-good-news

#965 Check if `result` is defined before logging.
  funcx_endpoint/funcx_endpoint/endpoint/interchange.py
Labels: no-news-is-good-news

#966 Bump version and changelog for release
  changelog.d/20221106_000523_kevin_remove_monkeypatch.rst
  changelog.d/20221107_105710_kevin_no_wrap_list_endpoint_id.rst
  docs/changelog.rst
  funcx_endpoint/funcx_endpoint/version.py
  funcx_sdk/funcx/version.py
Labels: no-news-is-good-news, quick-review

#967 Use convenience import in doc
  docs/quickstart.rst
Labels: no-news-is-good-news, quick-review

#962 Sc 19617 feature flag endpoints with multi tenant
  funcx_endpoint/funcx_endpoint/cli.py
  funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
  funcx_endpoint/funcx_endpoint/endpoint/interchange.py
  funcx_endpoint/funcx_endpoint/endpoint/register_endpoint.py
  funcx_endpoint/funcx_endpoint/endpoint/utils/config.py
  funcx_endpoint/tests/integration/funcx_endpoint/endpoint/test_endpoint_manager.py
  funcx_endpoint/tests/unit/test_register_endpoint.py
  funcx_sdk/funcx/sdk/client.py
  funcx_sdk/funcx/sdk/web_client.py
  funcx_sdk/tests/unit/test_web_client.py
Labels: no-news-is-good-news

#973 Update pre-commit config
  .pre-commit-config.yaml
Labels: no-news-is-good-news

#974 No sense in specifying the default ...
  funcx_endpoint/funcx_endpoint/endpoint/default_config.py
Labels: no-news-is-good-news, quick-review

#975 Stop passing around module
  funcx_endpoint/funcx_endpoint/cli.py
  funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
  funcx_endpoint/tests/integration/conftest.py
  funcx_endpoint/tests/integration/funcx_endpoint/endpoint/test_endpoint_manager.py
  funcx_endpoint/tests/unit/test_cli_behavior.py
Labels: no-news-is-good-news, quick-review
