Repository globus/globus-compute, pull requests merged in 2022-06, with the labels that each got.

#812 Convert EPStatusReport message to funcx_common.messagepack protocol
  funcx_endpoint/funcx_endpoint/endpoint/interchange.py
  funcx_endpoint/funcx_endpoint/endpoint/messages_compat.py
  funcx_endpoint/setup.py
  funcx_endpoint/tests/funcx_endpoint/endpoint/test_messages_compat.py
Labels: no-news-is-good-news

#813 Pin the exact version of funcx-common
  funcx_endpoint/setup.py
Labels: quick-review

#816 Bump websockets to v10.3.
  funcx_sdk/setup.py
Labels: dependencies, no-news-is-good-news, quick-review

#821 Fix mismatch that happens when web-service declares a queue as durable but tests do not
  funcx_endpoint/tests/conftest.py
  funcx_endpoint/tests/test_rabbit_mq/conftest.py
  funcx_endpoint/tests/test_rabbit_mq/result_queue_subscriber.py
Labels: no-news-is-good-news, quick-review

#826 Flip the default for offprocess_checker
  funcx_sdk/funcx/sdk/client.py
Labels: quick-review

#827 Update pre-commit.ci to point at 'rabbitmq'
  .pre-commit-config.yaml
Labels: no-news-is-good-news

#831 Fix smoke tests to work against prod
  smoke_tests/Makefile
  smoke_tests/tests/test_s3_indirect.py
  smoke_tests/tox.ini
Labels: no-news-is-good-news, quick-review

#832 Remove numpy from test deps
  funcx_sdk/setup.py
Labels: no-news-is-good-news, quick-review

#833 Remove all archived tests
  funcx_endpoint/setup.cfg
  funcx_endpoint/tests/archived/integration/reload.sh
  funcx_endpoint/tests/archived/integration/test.ipynb
  funcx_endpoint/tests/archived/integration/test_batch_submit.py
  funcx_endpoint/tests/archived/integration/test_client.py
  funcx_endpoint/tests/archived/integration/test_config.py
  funcx_endpoint/tests/archived/integration/test_containers.py
  funcx_endpoint/tests/archived/integration/test_deserialization.py
  funcx_endpoint/tests/archived/integration/test_executor_passthrough.py
  funcx_endpoint/tests/archived/integration/test_interchange.py
  funcx_endpoint/tests/archived/integration/test_per_func_batch.py
  funcx_endpoint/tests/archived/integration/test_registration.py
  funcx_endpoint/tests/archived/integration/test_serialization.py
  funcx_endpoint/tests/archived/integration/test_status.py
  funcx_endpoint/tests/archived/integration/test_submits.py
  funcx_endpoint/tests/archived/integration/test_throttling.py
  funcx_endpoint/tests/archived/stress_tests/README.rst
  funcx_endpoint/tests/archived/stress_tests/conftest.py
  funcx_endpoint/tests/archived/stress_tests/shared.py
  funcx_endpoint/tests/archived/stress_tests/test_batch.py
  funcx_endpoint/tests/archived/stress_tests/test_executor.py
  funcx_endpoint/tests/archived/stress_tests/test_executor_io.py
  funcx_endpoint/tests/archived/stress_tests/test_io_volume.py
  funcx_endpoint/tests/archived/stress_tests/test_multi_client_ep.py
  funcx_endpoint/tests/archived/stress_tests/test_raw.py
  funcx_endpoint/tests/archived/tests_from_within_package_dir/conftest.py
  funcx_endpoint/tests/archived/tests_from_within_package_dir/strategies/__init__.py
  funcx_endpoint/tests/archived/tests_from_within_package_dir/strategies/test_kube_simple.py
  funcx_endpoint/tests/archived/tests_from_within_package_dir/test_accelerators.py
  funcx_endpoint/tests/archived/tests_from_within_package_dir/test_cancel.py
  funcx_endpoint/tests/archived/tutorial_ep/test_tutotial_ep.py
  funcx_endpoint/tests/archived/version_mismatch_tests/README.rst
  funcx_endpoint/tests/archived/version_mismatch_tests/config.py
  funcx_endpoint/tests/archived/version_mismatch_tests/run_test_matrix.sh
  funcx_endpoint/tests/archived/version_mismatch_tests/test_mismatched.py
  funcx_endpoint/tests/archived/version_mismatch_tests/update_all.sh
  funcx_sdk/setup.cfg
  funcx_sdk/tests/archived/README.rst
  funcx_sdk/tests/archived/__init__.py
  funcx_sdk/tests/archived/fn_module.py
  funcx_sdk/tests/archived/test_async.py
  funcx_sdk/tests/archived/test_basic.py
  funcx_sdk/tests/archived/test_batch.py
  funcx_sdk/tests/archived/test_errors/__init__.py
  funcx_sdk/tests/archived/test_errors/test_invalid_endpoint.py
  funcx_sdk/tests/archived/test_errors/test_invalid_function.py
  funcx_sdk/tests/archived/test_executor.py
  funcx_sdk/tests/archived/test_fn_serialization.py
  funcx_sdk/tests/archived/test_longduration.py
  funcx_sdk/tests/archived/test_managerlost.py
  funcx_sdk/tests/archived/test_param_serialization.py
  funcx_sdk/tests/archived/test_performance/__init__.py
  funcx_sdk/tests/archived/test_performance/test_performance.py
  funcx_sdk/tests/archived/test_result_size.py
Labels: no-news-is-good-news, quick-review
