Repository globus/globus-compute, pull requests merged in 2022-09, with the labels that each got.

#886 Remove inappropriate parsl ScalingFailed exception usage
  funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
Labels: no-news-is-good-news

#911 NFC: namespace the typing hints
  funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
Labels: no-news-is-good-news, quick-review

#910 Remove artificial iteration and wait during submission
  funcx_sdk/funcx/sdk/executor.py
Labels: no-news-is-good-news, quick-review

#912 No sense in leaving the queue open
  funcx_endpoint/funcx_endpoint/executors/high_throughput/executor.py
  funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
Labels: no-news-is-good-news, quick-review

#914 Let unit tests be independent of integration needs
  funcx_endpoint/tests/conftest.py
  funcx_endpoint/tests/integration/conftest.py
  funcx_endpoint/tests/integration/funcx_endpoint/conftest.py
  funcx_endpoint/tests/integration/funcx_endpoint/endpoint/test_endpoint.py
  funcx_endpoint/tests/integration/funcx_endpoint/endpoint/test_endpoint_manager.py
  funcx_endpoint/tests/integration/funcx_endpoint/endpoint/test_interchange.py
  funcx_endpoint/tests/integration/funcx_endpoint/endpoint/test_interchange_with_rabbit.py
  funcx_endpoint/tests/integration/funcx_endpoint/endpoint/test_messages_compat.py
  funcx_endpoint/tests/integration/funcx_endpoint/endpoint/test_register_ep.py
  funcx_endpoint/tests/integration/funcx_endpoint/executors/high_throughput/test_funcx_manager.py
  funcx_endpoint/tests/integration/funcx_endpoint/executors/high_throughput/test_worker_map.py
  funcx_endpoint/tests/integration/funcx_endpoint/executors/mock_executors.py
  funcx_endpoint/tests/integration/test_rabbit_mq/result_queue_subscriber.py
  funcx_endpoint/tests/integration/test_rabbit_mq/task_queue_publisher.py
  funcx_endpoint/tests/integration/test_rabbit_mq/test_rabbit_e2e.py
  funcx_endpoint/tests/integration/test_rabbit_mq/test_result_q.py
  funcx_endpoint/tests/integration/test_rabbit_mq/test_result_q_heartbeat.py
  funcx_endpoint/tests/integration/test_rabbit_mq/test_task_q.py
  funcx_endpoint/tests/integration/test_rabbit_mq/test_task_q_shutdown.py
Labels: no-news-is-good-news, quick-review

#915 Remove dead code
  funcx_endpoint/funcx_endpoint/executors/high_throughput/executor.py
Labels: no-news-is-good-news, quick-review

#913 More robustly handle executor failure to start
  funcx_endpoint/funcx_endpoint/executors/high_throughput/executor.py
  funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
  funcx_endpoint/tests/unit/test_highthroughputinterchange.py
Labels: no-news-is-good-news, quick-review

#917 Avoid traceback if RMQ closes connection
  funcx_endpoint/funcx_endpoint/endpoint/interchange.py
  funcx_endpoint/funcx_endpoint/endpoint/rabbit_mq/result_queue_publisher.py
Labels: no-news-is-good-news, quick-review

#916 Give more direct description of problem
  funcx_sdk/funcx/sdk/login_manager/manager.py
  funcx_sdk/tests/unit/test_login_manager.py
Labels: no-news-is-good-news, quick-review

#918 Reduce log-level to debug
  funcx_sdk/funcx/sdk/executor.py
Labels: no-news-is-good-news, quick-review

#919 Rename variable for clarity
  funcx_sdk/funcx/sdk/executor.py
Labels: no-news-is-good-news, quick-review

#922 remove obsolete map_run and submit_batch
  funcx_sdk/funcx/sdk/client.py
  funcx_sdk/funcx/sdk/web_client.py
Labels: no-news-is-good-news, quick-review

#902 Add combined payload serialization from multiple methods
  funcx_sdk/funcx/serialize/base.py
  funcx_sdk/funcx/serialize/concretes.py
  funcx_sdk/tests/integration/test_serialization.py
Labels: no-news-is-good-news

#925 Fix endpoint configuration docstring default
  funcx_endpoint/funcx_endpoint/endpoint/utils/config.py
Labels: no-news-is-good-news, quick-review

#926 Reset after highlight
  funcx_endpoint/funcx_endpoint/logging_config.py
Labels: no-news-is-good-news, quick-review

#927 Add filesystem options to the Polaris example config.
  docs/configs/polaris.py
  docs/configuring.rst
Labels: Documentation, no-news-is-good-news

#929 Add `.task_count_submitted` to FuncXExecutor
  changelog.d/20220831_210735_kevin_add_submitted_task_counter.rst
  funcx_sdk/funcx/sdk/executor.py
Labels: quick-review

#932 Remove unnecessary test method separation
  funcx_endpoint/tests/integration/test_rabbit_mq/test_task_q.py
  funcx_endpoint/tests/integration/test_rabbit_mq/test_task_q_shutdown.py
Labels: no-news-is-good-news, quick-review

#930 Update the ManagerLost error handling to mimic function exceptions
  funcx_endpoint/funcx_endpoint/endpoint/messages_compat.py
  funcx_endpoint/funcx_endpoint/endpoint/rabbit_mq/result_queue_publisher.py
  funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
Labels: no-news-is-good-news

#928 Remove unnecessary data structure
  changelog.d/20220920_114304_kevin_refactor_executor_task_future_association.rst
  funcx_sdk/funcx/sdk/executor.py
  funcx_sdk/tests/unit/test_executor.py
Labels: quick-review

#931 Add a block comment to the FuncXExecutor class
  funcx_sdk/funcx/sdk/executor.py
Labels: no-news-is-good-news, quick-review

#934 Serialize access to sqlite
  changelog.d/20220921_161549_kevin_serialize_access_to_sqlite.rst
  funcx_sdk/funcx/sdk/login_manager/manager.py
  funcx_sdk/funcx/sdk/login_manager/tokenstore.py
Labels: quick-review

#935 Correct errant copy-paste-o
  funcx_endpoint/funcx_endpoint/logging_config.py
Labels: no-news-is-good-news, quick-review

#939 SC-19182 Fine-tune where we take the lock
  funcx_sdk/funcx/sdk/login_manager/manager.py
Labels: no-news-is-good-news, quick-review
