Repository globus/globus-compute, pull requests merged in 2022-03, with the labels that each got.

#694 Update release process: tox + tags
  funcx_endpoint/tox.ini
  funcx_sdk/tox.ini
  release.sh
  tag_and_release.sh
Labels: no-news-is-good-news

#707 Skip changelog check on pre-commit autoupdate PRs
  .github/workflows/changelog.yml
Labels: no-news-is-good-news, quick-review

#718 Show task uuid rather than Python object repr in pull_tasks dispatch
  funcx_endpoint/funcx_endpoint/executors/high_throughput/funcx_manager.py
Labels: no-news-is-good-news

#725 Increase the sdk dependency to >=3.6 to include the globus_sdk v3 dep
  funcx_endpoint/setup.py
Labels: no-news-is-good-news

#726 Reduce surprise level for expected log message
  funcx_endpoint/funcx_endpoint/executors/high_throughput/funcx_manager.py
Labels: no-news-is-good-news

#737 Remove unused testing code.
  funcx_sdk/funcx/sdk/executor.py
Labels: no-news-is-good-news

#736 Set attribute, not property
  funcx_sdk/funcx/sdk/asynchronous/ws_polling_task.py
  funcx_sdk/funcx/sdk/executor.py
  funcx_sdk/funcx/tests/unit/test_executor.py
  funcx_sdk/setup.py
Labels: no-news-is-good-news

#739 Remove incorrect manual thread identification from executor and add names on Threads
  funcx_sdk/funcx/sdk/executor.py
Labels: no-news-is-good-news

#741 Avoid possible crash during ws close
  funcx_sdk/funcx/sdk/asynchronous/ws_polling_task.py
  funcx_sdk/funcx/tests/unit/test_ws_poller.py
Labels: no-news-is-good-news

#742 Rename variables in FuncXExecutor for clarify
  funcx_sdk/funcx/sdk/executor.py
Labels: no-news-is-good-news

#743 Teach AtomicController to increase by n
  funcx_sdk/funcx/sdk/executor.py
  funcx_sdk/funcx/tests/unit/test_atomiccontroller.py
Labels: no-news-is-good-news

#744 Add some typing information
  funcx_sdk/funcx/sdk/asynchronous/ws_polling_task.py
  funcx_sdk/funcx/sdk/client.py
  funcx_sdk/funcx/sdk/executor.py
Labels: no-news-is-good-news, quick-review

#748 Remove useless else branch
  funcx_sdk/funcx/sdk/asynchronous/ws_polling_task.py
Labels: no-news-is-good-news, quick-review

#746 remove use of throttling_enabled in smoke_tests
  smoke_tests/tests/conftest.py
Labels: no-news-is-good-news

#749 Remove some redundancy
  funcx_sdk/funcx/sdk/executor.py
Labels: no-news-is-good-news, quick-review

#750 Remove support for python3.6
  .github/workflows/ci.yaml
  CONTRIBUTING.md
  changelog.d/20220331_173227_sirosen_drop_py36.rst
  docs/quickstart.rst
  funcx_endpoint/setup.py
  funcx_sdk/setup.py
  funcx_sdk/tox.ini
  runtime.txt
Labels: quick-review

#745 Convert executor internal message objects from dict to dedicated object
  funcx_sdk/funcx/sdk/executor.py
  funcx_sdk/funcx/tests/unit/test_executor.py
Labels: no-news-is-good-news

#747 Mild clarification of data structure parts
  funcx_sdk/funcx/sdk/executor.py
Labels: no-news-is-good-news, quick-review

#752 Reduce visual complexity of `.submit()`
  funcx_sdk/funcx/sdk/executor.py
Labels: no-news-is-good-news, quick-review

#751 Enable end-user to specify session id
  funcx_sdk/funcx/sdk/client.py
  funcx_sdk/funcx/tests/unit/test_client_init.py
Labels: no-news-is-good-news, quick-review
