Repository globus/globus-compute, pull requests merged in 2022-04, with the labels that each got.

#756 Reorganize 'funcx_sdk' tests so that tox is better
  funcx_sdk/setup.cfg
  funcx_sdk/tests/archived/README.rst
  funcx_sdk/tests/archived/__init__.py
  funcx_sdk/tests/archived/fn_module.py
  funcx_sdk/tests/archived/test_async.py
  funcx_sdk/tests/archived/test_basic.py
  funcx_sdk/tests/archived/test_batch.py
  funcx_sdk/tests/archived/test_errors/__init__.py
  funcx_sdk/tests/archived/test_errors/test_invalid_endpoint.py
  funcx_sdk/tests/archived/test_errors/test_invalid_function.py
  funcx_sdk/tests/archived/test_executor.py
  funcx_sdk/tests/archived/test_fn_serialization.py
  funcx_sdk/tests/archived/test_longduration.py
  funcx_sdk/tests/archived/test_managerlost.py
  funcx_sdk/tests/archived/test_param_serialization.py
  funcx_sdk/tests/archived/test_performance/__init__.py
  funcx_sdk/tests/archived/test_performance/test_performance.py
  funcx_sdk/tests/archived/test_result_size.py
  funcx_sdk/tests/conftest.py
  funcx_sdk/tests/integration/test_web_client_exceptions.py
  funcx_sdk/tests/unit/test_atomiccontroller.py
  funcx_sdk/tests/unit/test_client_init.py
  funcx_sdk/tests/unit/test_environment_lookups.py
  funcx_sdk/tests/unit/test_executor.py
  funcx_sdk/tests/unit/test_web_client.py
  funcx_sdk/tests/unit/test_ws_poller.py
  funcx_sdk/tox.ini
Labels: no-news-is-good-news, quick-review

#754 Remove distutils and reorganize version check
  funcx_endpoint/funcx_endpoint/__init__.py
  funcx_endpoint/funcx_endpoint/endpoint/endpoint_manager.py
  funcx_endpoint/funcx_endpoint/version.py
  funcx_endpoint/setup.py
  funcx_endpoint/tests/funcx_endpoint/endpoint/test_endpoint_manager.py
  funcx_sdk/funcx/__init__.py
  funcx_sdk/funcx/sdk/__init__.py
  funcx_sdk/funcx/sdk/client.py
  funcx_sdk/funcx/sdk/version.py
  funcx_sdk/setup.py
  funcx_sdk/tests/unit/test_version_parse.py
Labels: no-news-is-good-news

#759 Minor refactor to clarify class var intent
  funcx_sdk/funcx/sdk/client.py
Labels: no-news-is-good-news, quick-review

#761 An unused decoding. No need.
  funcx_endpoint/funcx_endpoint/endpoint/endpoint_manager.py
Labels: no-news-is-good-news, quick-review

#763 Mild variable name change.
  funcx_sdk/funcx/sdk/executor.py
Labels: no-news-is-good-news, quick-review

#760 Refactor _update_task_table.
  funcx_sdk/funcx/sdk/client.py
  funcx_sdk/tests/unit/test_client.py
  funcx_sdk/tests/unit/utils.py
Labels: no-news-is-good-news

#766 "Privatize" lock, update method signatures.
  funcx_sdk/funcx/sdk/executor.py
Labels: no-news-is-good-news, quick-review

#767 Teach AtomicController how to reset itself.
  funcx_sdk/funcx/sdk/executor.py
  funcx_sdk/tests/unit/test_atomiccontroller.py
Labels: no-news-is-good-news, quick-review

#764 No need for extra method.
  funcx_sdk/funcx/sdk/executor.py
Labels: no-news-is-good-news, quick-review

#769 Remove unused arguments.
  funcx_sdk/funcx/sdk/executor.py
Labels: no-news-is-good-news, quick-review

#765 Add coverage reporting to tox output for funcx
  funcx_sdk/.coveragerc
  funcx_sdk/setup.py
  funcx_sdk/tox.ini
Labels: no-news-is-good-news, quick-review

#773 Teach FuncXFuture to set the task_id in init.
  funcx_sdk/funcx/sdk/executor.py
Labels: no-news-is-good-news, quick-review

#771 PR template spelling typo
  .github/PULL_REQUEST_TEMPLATE.md
Labels: no-news-is-good-news, quick-review

#776 Ensure pending tasks are always requested
  funcx_sdk/funcx/sdk/client.py
  funcx_sdk/tests/unit/test_client.py
Labels: no-news-is-good-news, quick-review

#770 Remove type ambiguity in ExecutorPollerThread
  funcx_sdk/funcx/sdk/asynchronous/ws_polling_task.py
  funcx_sdk/funcx/sdk/executor.py
Labels: no-news-is-good-news

#775 Use new secrets file for k8s endpoint
  helm/boot.sh
Labels: no-news-is-good-news

#727 SC-11102 Implement task group rehydration.
  changelog.d/20220325_154137_kevin_ReloadTaskGroup.rst
  funcx_sdk/funcx/sdk/asynchronous/ws_polling_task.py
  funcx_sdk/funcx/sdk/client.py
  funcx_sdk/funcx/sdk/executor.py
  funcx_sdk/funcx/sdk/web_client.py
  funcx_sdk/tests/unit/test_executor.py
  funcx_sdk/tests/unit/test_ws_poller.py
Labels: enhancement

#785 Remove texttable from funcx deps
  funcx_sdk/setup.py
Labels: no-news-is-good-news, quick-review

#784 Cleanup config for running endpoint tests
  funcx_endpoint/setup.cfg
  funcx_endpoint/tests/archived/integration/reload.sh
  funcx_endpoint/tests/archived/integration/test.ipynb
  funcx_endpoint/tests/archived/integration/test_batch_submit.py
  funcx_endpoint/tests/archived/integration/test_client.py
  funcx_endpoint/tests/archived/integration/test_config.py
  funcx_endpoint/tests/archived/integration/test_containers.py
  funcx_endpoint/tests/archived/integration/test_deserialization.py
  funcx_endpoint/tests/archived/integration/test_executor_passthrough.py
  funcx_endpoint/tests/archived/integration/test_interchange.py
  funcx_endpoint/tests/archived/integration/test_per_func_batch.py
  funcx_endpoint/tests/archived/integration/test_registration.py
  funcx_endpoint/tests/archived/integration/test_serialization.py
  funcx_endpoint/tests/archived/integration/test_status.py
  funcx_endpoint/tests/archived/integration/test_submits.py
  funcx_endpoint/tests/archived/integration/test_throttling.py
  funcx_endpoint/tests/archived/stress_tests/README.rst
  funcx_endpoint/tests/archived/stress_tests/conftest.py
  funcx_endpoint/tests/archived/stress_tests/shared.py
  funcx_endpoint/tests/archived/stress_tests/test_batch.py
  funcx_endpoint/tests/archived/stress_tests/test_executor.py
  funcx_endpoint/tests/archived/stress_tests/test_executor_io.py
  funcx_endpoint/tests/archived/stress_tests/test_io_volume.py
  funcx_endpoint/tests/archived/stress_tests/test_multi_client_ep.py
  funcx_endpoint/tests/archived/stress_tests/test_raw.py
  funcx_endpoint/tests/archived/tests_from_within_package_dir/conftest.py
  funcx_endpoint/tests/archived/tests_from_within_package_dir/strategies/__init__.py
  funcx_endpoint/tests/archived/tests_from_within_package_dir/strategies/test_kube_simple.py
  funcx_endpoint/tests/archived/tests_from_within_package_dir/test_accelerators.py
  funcx_endpoint/tests/archived/tests_from_within_package_dir/test_cancel.py
  funcx_endpoint/tests/archived/tutorial_ep/test_tutotial_ep.py
  funcx_endpoint/tests/archived/version_mismatch_tests/README.rst
  funcx_endpoint/tests/archived/version_mismatch_tests/config.py
  funcx_endpoint/tests/archived/version_mismatch_tests/run_test_matrix.sh
  funcx_endpoint/tests/archived/version_mismatch_tests/test_mismatched.py
  funcx_endpoint/tests/archived/version_mismatch_tests/update_all.sh
  funcx_endpoint/tests/funcx_endpoint/endpoint/test_endpoint.py
  funcx_endpoint/tests/funcx_endpoint/endpoint/test_interchange.py
  funcx_endpoint/tox.ini
Labels: no-news-is-good-news, quick-review

#786 Improve version comparison rules
  funcx_sdk/funcx/sdk/client.py
  funcx_sdk/funcx/sdk/version.py
  funcx_sdk/tests/unit/test_version_parse.py
Labels: no-news-is-good-news, quick-review

#792 Don't try to close channel if connection failed
  funcx_endpoint/funcx_endpoint/endpoint/rabbit_mq/result_queue_publisher.py
Labels: no-news-is-good-news, quick-review

#793 Fix FuncXExecutor docstring that was causing sphinx errors
  funcx_sdk/funcx/sdk/executor.py
Labels: no-news-is-good-news, quick-review

#794 Fix graceful endpoint shutdown
  funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
  funcx_endpoint/funcx_endpoint/endpoint/interchange.py
  funcx_endpoint/funcx_endpoint/endpoint/rabbit_mq/task_queue_subscriber.py
  funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
  funcx_endpoint/tests/funcx_endpoint/endpoint/test_interchange.py
Labels: no-news-is-good-news
