Repository globus/globus-compute, pull requests merged in 2022-08, with the labels that each got.

#864 remove references to forwarder and the 3 zmq ports
  docs/debugging.rst
  docs/endpoints.rst
  docs/index.rst
Labels: Documentation, no-news-is-good-news, quick-review

#867 Mistakenly lost interpolation variable
  funcx_endpoint/funcx_endpoint/cli.py
Labels: no-news-is-good-news, quick-review

#862 Endpoint Helm Chart Uses Correct funcx-endpoint-uuid command line arg
  helm/boot.sh
Labels: no-news-is-good-news, quick-review

#868 Forget the acked results
  funcx_endpoint/funcx_endpoint/endpoint/interchange.py
Labels: no-news-is-good-news, quick-review

#796 Improve forwarding performance with threads
  funcx_endpoint/funcx_endpoint/endpoint/interchange.py
Labels: no-news-is-good-news

#865 Skip the broken endpoint status test
  smoke_tests/tests/test_version.py
Labels: no-news-is-good-news

#871 Remove unused variable.
  funcx_endpoint/funcx_endpoint/executors/high_throughput/executor.py
Labels: no-news-is-good-news, quick-review

#872 Use correct variable: period, not threshold
  funcx_endpoint/funcx_endpoint/endpoint/interchange.py
Labels: no-news-is-good-news, quick-review

#873 Correct endpoint shutdown logic
  funcx_endpoint/funcx_endpoint/endpoint/interchange.py
Labels: no-news-is-good-news, quick-review

#875 Refactor class variable name
  funcx_endpoint/funcx_endpoint/endpoint/interchange.py
  funcx_endpoint/funcx_endpoint/endpoint/rabbit_mq/task_queue_subscriber.py
  funcx_endpoint/tests/test_rabbit_mq/conftest.py
  funcx_endpoint/tests/test_rabbit_mq/test_rabbit_e2e.py
  funcx_endpoint/tests/test_rabbit_mq/test_task_q.py
Labels: no-news-is-good-news, quick-review

#874 Update mac_safe_queue import for new Parsl version
  funcx_endpoint/funcx_endpoint/executors/high_throughput/mac_safe_queue.py
Labels: no-news-is-good-news, quick-review

#877 Provide a little more help in error case
  funcx_endpoint/funcx_endpoint/endpoint/interchange.py
Labels: no-news-is-good-news, quick-review

#849 Use FuncxTaskExecutionFailed in executor mode
  funcx_sdk/funcx/sdk/asynchronous/ws_polling_task.py
Labels: no-news-is-good-news

#880 Updates to funcx for 1.0.0a0 release updates
  funcx_sdk/funcx/version.py
  funcx_sdk/setup.py
Labels: no-news-is-good-news

#882 Updating version to 1.0.0a0
  funcx_endpoint/funcx_endpoint/version.py
Labels: no-news-is-good-news

#881 v1.0.0a0-release updates
  funcx_endpoint/funcx_endpoint/version.py
  funcx_endpoint/setup.py
  funcx_sdk/funcx/version.py
  funcx_sdk/setup.py
Labels: no-news-is-good-news

#884 Default to None to let lib choose default
  changelog.d/20220816_152320_kevin_default_to_spoa_namespace.rst
  funcx_endpoint/funcx_endpoint/endpoint/utils/config.py
Labels: quick-review

#883 V1.0.0 release
  changelog.d/20220705_163242_chris_funcx_client_url_mismatch.rst
  changelog.d/20220706_095230_LeiGlobus_off_process_checker_removal_sc_13659.rst
  changelog.d/20220715_160834_kevin_update_status_delta_per_fx_common_change.rst
  changelog.d/20220720_141209_benc_benc_parsl_dep_master.rst
  changelog.d/20220803_105233_ben_working_dir_for_workers.rst
  docs/changelog.rst
  funcx_endpoint/funcx_endpoint/version.py
  funcx_endpoint/setup.py
  funcx_sdk/funcx/version.py
Labels: no-news-is-good-news

#885 Release v1.0.1
  funcx_endpoint/funcx_endpoint/version.py
Labels: no-news-is-good-news, quick-review

#887 A cleaner endpoint quit from the CLI
  funcx_endpoint/funcx_endpoint/endpoint/interchange.py
Labels: no-news-is-good-news, quick-review

#889 Update the example config for Polaris
  docs/configs/polaris.py
Labels: Documentation, no-news-is-good-news

#891 provide default values for exec_.._ms to avoid keyerror
  funcx_endpoint/funcx_endpoint/endpoint/messages_compat.py
Labels: no-news-is-good-news, quick-review

#892 Use non-deprecated RMQ health check
  .github/workflows/ci.yaml
Labels: no-news-is-good-news, quick-review

#893 Show error-level logs in tests
  .github/workflows/ci.yaml
Labels: no-news-is-good-news, quick-review

#895 Release v1.0.2
  changelog.d/20220812_135317_yadudoc1729_persist_results.rst
  changelog.d/20220816_152320_kevin_default_to_spoa_namespace.rst
  changelog.d/20220817_134952_yadudoc1729_serialization_fixes.rst
  docs/changelog.rst
  funcx_endpoint/funcx_endpoint/version.py
Labels: quick-review

#896 Bump SDK version for release.
  funcx_sdk/funcx/version.py
Labels: no-news-is-good-news, quick-review

#899 Remove credentials from logs
  funcx_endpoint/funcx_endpoint/endpoint/rabbit_mq/task_queue_subscriber.py
  funcx_endpoint/funcx_endpoint/endpoint/register_endpoint.py
Labels: no-news-is-good-news, quick-review

#898 Missing variable refactor
  funcx_endpoint/funcx_endpoint/endpoint/rabbit_mq/task_queue_subscriber.py
Labels: no-news-is-good-news, quick-review

#900 Remove test-flag in production code
  funcx_endpoint/funcx_endpoint/endpoint/interchange.py
  funcx_endpoint/tests/funcx_endpoint/endpoint/test_interchange.py
Labels: no-news-is-good-news, quick-review

#904 Enable logging to console
  changelog.d/20220820_232432_kevin_log_to_console.rst
  changelog.d/20220824_221225_kevin_log_to_console.rst
  funcx_endpoint/funcx_endpoint/cli.py
  funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
  funcx_endpoint/funcx_endpoint/logging_config.py
  funcx_endpoint/tests/funcx_endpoint/endpoint/test_endpoint_manager.py
Labels: quick-review
