Repository globus/globus-compute, pull requests merged in 2022-10, with the labels that each got.

#941 check jupyter notebook in addition to tty
  funcx_sdk/funcx/sdk/login_manager/manager.py
Labels: no-news-is-good-news, quick-review

#937 Bump versions and changelog for release v1.0.4
  changelog.d/20220831_210735_kevin_add_submitted_task_counter.rst
  changelog.d/20220907_150940_chris_dont_require_client_argument.rst
  changelog.d/20220908_132611_LeiGlobus_websocket_queue_flag_sc_15524.rst
  changelog.d/20220920_114304_kevin_refactor_executor_task_future_association.rst
  changelog.d/20220921_161549_kevin_serialize_access_to_sqlite.rst
  docs/changelog.rst
  funcx_endpoint/funcx_endpoint/version.py
  funcx_endpoint/setup.py
  funcx_sdk/funcx/version.py
Labels: no-news-is-good-news, quick-review

#938 Venv environment doc changes
  docs/Tutorial.rst
  docs/endpoints.rst
  docs/executor.rst
  docs/index.rst
  docs/quickstart.rst
  docs/sdk.rst
Labels: Documentation, no-news-is-good-news, quick-review

#940 Refactor `Batch.add()` interface
  changelog.d/20220930_151519_kevin_batch_add_interface_cleanup.rst
  funcx_sdk/funcx/sdk/batch.py
  funcx_sdk/funcx/sdk/client.py
  funcx_sdk/funcx/sdk/executor.py
  funcx_sdk/tests/unit/test_client.py
Labels: quick-review

#944 Pass the HTEX interchange an existing FuncXClient
  funcx_endpoint/funcx_endpoint/endpoint/interchange.py
  funcx_endpoint/funcx_endpoint/executors/high_throughput/executor.py
  funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
  funcx_endpoint/tests/integration/funcx_endpoint/executors/mock_executors.py
  funcx_endpoint/tests/unit/test_highthroughputinterchange.py
Labels: no-news-is-good-news

#945 Refactor internal data structure
  funcx_sdk/funcx/sdk/batch.py
Labels: no-news-is-good-news, quick-review

#947 Address recent batch.add inteface change
  smoke_tests/tests/test_running_functions.py
Labels: no-news-is-good-news, quick-review

#948 Update client docs
  docs/endpoints.rst
  docs/sdk.rst
Labels: Documentation, no-news-is-good-news

#950 Fix hourly smoketest
  smoke_tests/tests/test_running_functions.py
Labels: no-news-is-good-news, quick-review
