Repository globus/globus-compute, pull requests merged in 2023-08, with the labels that each got.

#1242 Implement admin-specified user-endpoint env
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
  compute_endpoint/tests/unit/test_endpointmanager_unit.py
Labels: no-news-is-good-news, quick-review

#1251 Address slow test
  compute_endpoint/tests/integration/endpoint/endpoint/test_interchange.py
Labels: no-news-is-good-news, quick-review

#1252 Remove unpack() in endpoint/interchange
  compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
  compute_endpoint/globus_compute_endpoint/engines/base.py
  compute_endpoint/globus_compute_endpoint/engines/high_throughput/engine.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_interchange.py
  compute_endpoint/tests/integration/endpoint/executors/high_throughput/test_htex_regression.py
  compute_endpoint/tests/integration/endpoint/executors/mock_executors.py
  compute_endpoint/tests/unit/test_engines.py
  compute_endpoint/tests/unit/test_status_reporting.py
Labels: no-news-is-good-news

#1254 Bump versions for v2.3.0a0 release
  compute_endpoint/globus_compute_endpoint/version.py
  compute_endpoint/setup.py
  compute_funcx/endpoint/funcx_endpoint/version.py
  compute_funcx/endpoint/setup.py
  compute_funcx/sdk/funcx/version.py
  compute_funcx/sdk/setup.py
  compute_sdk/globus_compute_sdk/version.py
Labels: no-news-is-good-news, quick-review

#1256 Use pathlib object
  compute_endpoint/globus_compute_endpoint/endpoint/config/utils.py
Labels: no-news-is-good-news, quick-review

#1257 Move ClickException to closer to the CLI
  compute_endpoint/globus_compute_endpoint/endpoint/config/utils.py
Labels: no-news-is-good-news, quick-review

#1258 Redact credentials from log emission
  compute_endpoint/globus_compute_endpoint/endpoint/rabbit_mq/command_queue_subscriber.py
  compute_endpoint/tests/unit/test_command_queue_subscriber.py
Labels: no-news-is-good-news, quick-review

#1259 Revert dill version to make it compatible with 2.2.3
  compute_sdk/setup.py
Labels: no-news-is-good-news, quick-review

#1255 Address cross-thread access to Pika
  compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
  compute_endpoint/globus_compute_endpoint/endpoint/rabbit_mq/__init__.py
  compute_endpoint/globus_compute_endpoint/endpoint/rabbit_mq/result_publisher.py
  compute_endpoint/globus_compute_endpoint/endpoint/rabbit_mq/result_queue_publisher.py
  compute_endpoint/tests/integration/conftest.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_interchange.py
  compute_endpoint/tests/integration/test_rabbit_mq/test_result_q.py
  compute_endpoint/tests/integration/test_rabbit_mq/test_result_q_heartbeat.py
  compute_endpoint/tests/unit/test_result_publisher.py
  compute_endpoint/tests/unit/test_result_queue_publisher.py
Labels: no-news-is-good-news

#1261 Escape user option strings to avoid YAML injection
  compute_endpoint/globus_compute_endpoint/endpoint/config/utils.py
  compute_endpoint/tests/unit/test_endpoint_unit.py
  compute_endpoint/tests/unit/test_endpointmanager_unit.py
Labels: no-news-is-good-news

#1262 Evaluate untrusted code in Jinja sandbox
  compute_endpoint/globus_compute_endpoint/endpoint/config/utils.py
  compute_endpoint/tests/unit/test_endpointmanager_unit.py
Labels: no-news-is-good-news

#1263 Create default templates for MT endpoints
  compute_endpoint/globus_compute_endpoint/endpoint/config/user_config_template.yaml
  compute_endpoint/globus_compute_endpoint/endpoint/config/user_environment.yaml
  compute_endpoint/globus_compute_endpoint/endpoint/config/utils.py
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint_manager.py
  compute_endpoint/tests/unit/test_cli_behavior.py
  compute_endpoint/tests/unit/test_endpoint_unit.py
  compute_endpoint/tests/unit/test_endpointmanager_unit.py
Labels: no-news-is-good-news

#1265 Bump versions and changelog for release v2.3.0
  changelog.d/20230718_143645_chris_batchv3.rst
  changelog.d/20230720_143409_30907815+rjmello_self_diagnostic.rst
  changelog.d/20230724_145257_LeiGlobus_registration_blocked_msg_sc_25245.rst
  changelog.d/20230725_113122_chris_batch_selectable_ser.rst
  changelog.d/20230725_150822_chris_cleanup_client_init.rst
  changelog.d/20230731_100321_kevin_avoid_possible_tg_race_condition.rst
  changelog.d/20230802_150602_yadudoc1729_fix_missing_script_dir.rst
  compute_endpoint/globus_compute_endpoint/version.py
  compute_endpoint/setup.py
  compute_funcx/endpoint/funcx_endpoint/version.py
  compute_funcx/endpoint/setup.py
  compute_funcx/sdk/funcx/version.py
  compute_funcx/sdk/setup.py
  compute_sdk/globus_compute_sdk/version.py
  docs/changelog.rst
  docs/changelog_funcx.rst
Labels: no-news-is-good-news, quick-review

#1264 Create Jinja filter to escape shell commands
  compute_endpoint/globus_compute_endpoint/endpoint/config/utils.py
  compute_endpoint/tests/unit/test_endpointmanager_unit.py
Labels: no-news-is-good-news

#1260 Switch to the latest tutorial notebook as the example.
  docs/Tutorial.rst
Labels: Documentation, no-news-is-good-news

#1270 Ensure matching types in TG UUID comparison
  changelog.d/20230814_175226_30907815+rjmello_HEAD.rst
  compute_sdk/globus_compute_sdk/sdk/executor.py
  compute_sdk/tests/unit/test_executor.py
Labels: no-news-is-good-news, quick-review

#1268 Fix smoke tests and `Executor.reload_tasks`
  smoke_tests/tests/test_running_functions.py
Labels: bug, no-news-is-good-news, quick-review

#1266 Prevent same-user child-processes
  compute_endpoint/globus_compute_endpoint/endpoint/config/config.py
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
  compute_endpoint/globus_compute_endpoint/endpoint/utils/__init__.py
  compute_endpoint/setup.py
  compute_endpoint/tests/unit/test_endpointmanager_unit.py
  compute_endpoint/tests/unit/test_utils.py
Labels: no-news-is-good-news, quick-review

#1273 Add note to method serialization strategies
  docs/sdk.rst
Labels: Documentation, no-news-is-good-news

#1274 Add allowed functions to EP registration request
  compute_endpoint/globus_compute_endpoint/endpoint/config/config.py
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint.py
  compute_sdk/globus_compute_sdk/sdk/client.py
  compute_sdk/globus_compute_sdk/sdk/web_client.py
Labels: no-news-is-good-news

#1279 Make sure combinedCode works when serialization fails
  compute_sdk/globus_compute_sdk/serialize/concretes.py
  compute_sdk/tests/integration/test_serialization.py
Labels: no-news-is-good-news

#1281 Print message to stdout when network error occurs
  changelog.d/20230824_124226_30907815+rjmello_HEAD.rst
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
  compute_endpoint/tests/unit/test_endpoint_unit.py
Labels: quick-review

#1282 Allow macOS to test
  compute_endpoint/globus_compute_endpoint/cli.py
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
  compute_endpoint/globus_compute_endpoint/endpoint/utils/__init__.py
  compute_endpoint/tests/unit/test_endpointmanager_unit.py
  compute_endpoint/tests/unit/test_utils.py
Labels: no-news-is-good-news

#1277 Add tutorial for systemd service
  docs/endpoints.rst
Labels: no-news-is-good-news
