Repository globus/globus-compute, pull requests merged in 2023-07, with the labels that each got.

#1208 Fix broken test
  compute_endpoint/globus_compute_endpoint/cli.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint.py
Labels: no-news-is-good-news, quick-review

#1209 Pin click to <= 8.1.3 due to mypy issues with 8.1.4
  compute_endpoint/setup.py
Labels: no-news-is-good-news

#1207 Bumping version to v2.2.3
  changelog.d/20230626_135706_yadudoc1729_unfork_htex_3.rst
  changelog.d/20230628_132155_chris_endpoint_setup_teardown.rst
  changelog.d/20230630_110417_30907815+rjmello_HEAD.rst
  compute_endpoint/globus_compute_endpoint/version.py
  compute_endpoint/setup.py
  compute_funcx/endpoint/funcx_endpoint/version.py
  compute_funcx/endpoint/setup.py
  compute_funcx/sdk/funcx/version.py
  compute_funcx/sdk/setup.py
  compute_sdk/globus_compute_sdk/version.py
  docs/changelog.rst
  docs/changelog_funcx.rst
Labels: no-news-is-good-news

#1210 Update mypy
  compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
  compute_endpoint/globus_compute_endpoint/engines/thread_pool.py
  compute_endpoint/setup.py
  compute_endpoint/tox.ini
Labels: no-news-is-good-news, quick-review

#1202 Adding delta config to docs.
  docs/_static/images/delta_front.png
  docs/configs/delta.yaml
  docs/configuring.rst
Labels: no-news-is-good-news

#1206 Update Parsl version to 2023.7.3
  .github/workflows/ci.yaml
  .github/workflows/daily.yaml
  .github/workflows/hourly.yaml
  .github/workflows/smoke_test.yaml
  changelog.d/20230705_141150_kevin_update_locked_parsl_version.rst
  compute_endpoint/globus_compute_endpoint/cli.py
  compute_endpoint/globus_compute_endpoint/engines/high_throughput/engine.py
  compute_endpoint/setup.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint.py
  compute_endpoint/tox.ini
  compute_sdk/setup.py
  compute_sdk/tests/integration/test_serialization.py
  compute_sdk/tox.ini
Labels: quick-review

#1203 Adding configs for Stampede2@TACC
  docs/_static/images/stampede2.jpg
  docs/configs/stampede2.yaml
  docs/configuring.rst
Labels: no-news-is-good-news

#1212 Explicitly define engine type in example configs
  docs/configs/delta.yaml
  docs/configs/stampede2.yaml
Labels: Documentation, no-news-is-good-news, quick-review

#1214 Update preview domain from globuscs.info to globus.org
  compute_sdk/globus_compute_sdk/sdk/_environments.py
  compute_sdk/tests/unit/test_environment_lookups.py
Labels: no-news-is-good-news, quick-review

#1216 Make the provider config field optional
  compute_endpoint/globus_compute_endpoint/endpoint/config/model.py
Labels: bug, no-news-is-good-news, quick-review

#1217 Add changelog for optional provider field bugfix
  changelog.d/20230714_103852_30907815+rjmello_optional_provider.rst
Labels: Documentation, quick-review

#1215 Adding config docs for Anvil at Purdue
  docs/_static/images/anvil.jpeg
  docs/configs/anvil.yaml
  docs/configuring.rst
Labels: no-news-is-good-news

#1213 Adding configuration docs for Expanse @ SDSC
  docs/_static/images/expanse.jpeg
  docs/configs/expanse.yaml
  docs/configuring.rst
Labels: no-news-is-good-news

#1218 v2.2.4a0 release and modify release scripts to have ignore changelog …
  compute_endpoint/globus_compute_endpoint/version.py
  compute_endpoint/setup.py
  compute_funcx/endpoint/funcx_endpoint/version.py
  compute_funcx/endpoint/setup.py
  compute_funcx/release.sh
  compute_funcx/sdk/funcx/version.py
  compute_funcx/sdk/setup.py
  compute_sdk/globus_compute_sdk/version.py
  release.sh
Labels: no-news-is-good-news, quick-review

#1223 Fix issue of using the string 'None' instead of None in default displ…
  compute_endpoint/globus_compute_endpoint/endpoint/config/default_config.yaml
  compute_endpoint/globus_compute_endpoint/endpoint/config/utils.py
  compute_endpoint/tests/unit/test_cli_behavior.py
Labels: no-news-is-good-news, quick-review

#1224 NFC: DRY some test text strings
  compute_sdk/tests/unit/test_executor.py
Labels: no-news-is-good-news, quick-review

#1227 Update interface used in Perlmutter example config
  docs/configs/perlmutter.yaml
Labels: Documentation, no-news-is-good-news, quick-review

#1229 Submit JSON `null`, not `"None"`
  compute_sdk/globus_compute_sdk/sdk/executor.py
  compute_sdk/tests/unit/test_executor.py
Labels: no-news-is-good-news, quick-review

#1230 Add bookend sentinels to log
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
  compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
  compute_endpoint/globus_compute_endpoint/engines/high_throughput/engine.py
  compute_endpoint/globus_compute_endpoint/engines/high_throughput/interchange.py
Labels: no-news-is-good-news, quick-review

#1231 Skip test until published SDK catches up
  smoke_tests/tests/test_running_functions.py
Labels: no-news-is-good-news, quick-review

#1232 Make that 2.2.5. *sigh*
  smoke_tests/tests/test_running_functions.py
Labels: no-news-is-good-news, quick-review

#1234 Use Python to get path of binary for interpreter
  compute_endpoint/globus_compute_endpoint/self_diagnostic.py
Labels: no-news-is-good-news, quick-review

#1235 Fix changelog formatting
  changelog.d/20230718_143645_chris_batchv3.rst
Labels: quick-review

#1228 Add console message for locked/conflict messages
  changelog.d/20230724_145257_LeiGlobus_registration_blocked_msg_sc_25245.rst
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
  compute_endpoint/tests/unit/test_endpoint_unit.py
Labels: quick-review

#1237 Reuse serializer
  compute_sdk/globus_compute_sdk/sdk/batch.py
Labels: no-news-is-good-news, quick-review

#1239 Coalesce to the UUID_TYPE_T
  compute_sdk/globus_compute_sdk/sdk/web_client.py
Labels: no-news-is-good-news, quick-review

#1238 Small typing addition
  compute_sdk/globus_compute_sdk/sdk/batch.py
  compute_sdk/globus_compute_sdk/sdk/client.py
Labels: no-news-is-good-news, quick-review

#1240 Update API route to v3 submit
  changelog.d/20230718_143645_chris_batchv3.rst
  compute_sdk/globus_compute_sdk/sdk/batch.py
  compute_sdk/globus_compute_sdk/sdk/client.py
  compute_sdk/globus_compute_sdk/sdk/executor.py
  compute_sdk/globus_compute_sdk/sdk/web_client.py
  compute_sdk/tests/unit/test_client.py
  compute_sdk/tests/unit/test_executor.py
Labels: no-news-is-good-news, quick-review

#1244 Remove obsolete recommendation to run endpoint stop twice
  docs/endpoints.rst
Labels: no-news-is-good-news, quick-review

#1245 Remove test for now-gone attribute
  compute_sdk/tests/unit/test_executor.py
Labels: no-news-is-good-news, quick-review

#1248 Address race-condition w/ Executor task submission
  changelog.d/20230731_100321_kevin_avoid_possible_tg_race_condition.rst
  compute_sdk/globus_compute_sdk/sdk/executor.py
  compute_sdk/tests/unit/test_executor.py
Labels: quick-review

#1241 Enforce allowed_functions locally on endpoint as redundancy to web_service checking
  compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
  compute_endpoint/globus_compute_endpoint/endpoint/rabbit_mq/task_queue_subscriber.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_interchange.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_interchange_with_rabbit.py
  compute_endpoint/tests/integration/test_rabbit_mq/test_rabbit_e2e.py
  compute_endpoint/tests/integration/test_rabbit_mq/test_task_q.py
Labels: no-news-is-good-news

#1250 Address advertised typing
  compute_sdk/globus_compute_sdk/sdk/client.py
Labels: no-news-is-good-news, quick-review
