Repository globus/globus-compute, pull requests merged in 2023-11, with the labels that each got.

#1345 Speed-up test by slicing time.sleep
  compute_endpoint/tests/unit/test_worker.py
Labels: no-news-is-good-news, quick-review

#1346 Refactor test
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint.py
Labels: no-news-is-good-news, quick-review

#1347 Correct test path of interest
  compute_endpoint/tests/unit/test_endpointmanager_unit.py
Labels: no-news-is-good-news, quick-review

#1348 Quiet some test output
  compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint_manager.py
  compute_endpoint/tests/integration/endpoint/executors/high_throughput/test_manager.py
  compute_endpoint/tests/integration/test_rabbit_mq/test_task_q.py
  compute_endpoint/tests/unit/test_bad_endpoint_config.py
  compute_endpoint/tests/unit/test_command_queue_subscriber.py
  compute_endpoint/tests/unit/test_endpointinterchange.py
  compute_endpoint/tests/unit/test_endpointmanager_unit.py
  compute_endpoint/tests/unit/test_execute_task.py
  compute_endpoint/tests/unit/test_worker.py
  compute_endpoint/tox.ini
Labels: no-news-is-good-news

#1344 Implement identity mapping
  compute_endpoint/globus_compute_endpoint/endpoint/config/config.py
  compute_endpoint/globus_compute_endpoint/endpoint/config/example_identity_mapping_config.json
  compute_endpoint/globus_compute_endpoint/endpoint/config/model.py
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
  compute_endpoint/globus_compute_endpoint/endpoint/identity_mapper.py
  compute_endpoint/setup.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint_manager.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_interchange.py
  compute_endpoint/tests/unit/conftest.py
  compute_endpoint/tests/unit/test_cli_behavior.py
  compute_endpoint/tests/unit/test_endpoint_config.py
  compute_endpoint/tests/unit/test_endpointmanager_unit.py
  compute_endpoint/tests/unit/test_identity_mapper.py
Labels: no-news-is-good-news

#1351 Fix two assertions
  compute_sdk/tests/unit/test_client.py
Labels: no-news-is-good-news, quick-review

#1352 Pass `label` to Parsl HTEX
  changelog.d/20231106_152114_30907815+rjmello_gcengine_label_passthrough.rst
  compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
  compute_endpoint/tests/unit/test_engines.py
Labels: bug, quick-review

#1355 Add container location to internal `Task` object
  compute_endpoint/globus_compute_endpoint/engines/high_throughput/engine.py
  compute_endpoint/tests/unit/test_htex.py
Labels: bug, no-news-is-good-news

#1354 Bump versions for 2.7.0 release and remove _funcx related notes
  RELEASING.md
  changelog.d/20230902_101610_rchard_add_token_login_manager.rst
  changelog.d/20231020_110321_chris_443_ampqs.rst
  changelog.d/20231025_205335_30907815+rjmello_gcengine_status.rst
  changelog.d/20231106_152114_30907815+rjmello_gcengine_label_passthrough.rst
  changelog.d/20231106_203334_30907815+rjmello.rst
  compute_endpoint/globus_compute_endpoint/version.py
  compute_endpoint/setup.py
  compute_sdk/globus_compute_sdk/version.py
  compute_sdk/setup.py
  docs/changelog.rst
Labels: quick-review

#1357 Release/v2.7.0
  docs/changelog.rst
Labels: no-news-is-good-news

#1359 Add missing files to manifest
  compute_endpoint/MANIFEST.in
Labels: no-news-is-good-news, quick-review

#1360 Read template before dropping privs
  compute_endpoint/globus_compute_endpoint/endpoint/config/utils.py
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
  compute_endpoint/tests/unit/test_endpoint_unit.py
  compute_endpoint/tests/unit/test_endpointmanager_unit.py
  compute_sdk/globus_compute_sdk/sdk/login_manager/tokenstore.py
Labels: no-news-is-good-news, quick-review

#1361 Rename test
  compute_endpoint/tests/unit/test_endpointmanager_unit.py
Labels: no-news-is-good-news, quick-review

#1363 Pass `address` to Parsl HTEX via `kwargs` catch-all
  compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
  compute_endpoint/globus_compute_endpoint/engines/process_pool.py
  compute_endpoint/globus_compute_endpoint/engines/thread_pool.py
Labels: no-news-is-good-news, quick-review

#1358 Add amqp changelog sc 28353
  docs/changelog.rst
Labels: Documentation, no-news-is-good-news, quick-review

#1362 remove references to sharing endpoints
  docs/endpoints.rst
  docs/executor.rst
  docs/quickstart.rst
  docs/sdk.rst
  docs/tutorial.rst
Labels: Documentation, no-news-is-good-news

#1369 Add missing schema file to configure output
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
Labels: no-news-is-good-news, quick-review

#1368 First go-round at MU instructions
  compute_endpoint/globus_compute_endpoint/MULTIUSER_SETUP.md
Labels: no-news-is-good-news

#1367 Centralize location of serialization/deserialization errors
  compute_sdk/globus_compute_sdk/errors/__init__.py
  compute_sdk/globus_compute_sdk/errors/error_types.py
  compute_sdk/globus_compute_sdk/serialize/base.py
  compute_sdk/globus_compute_sdk/serialize/concretes.py
  compute_sdk/globus_compute_sdk/serialize/facade.py
  compute_sdk/tests/integration/test_serialization.py
Labels: no-news-is-good-news, quick-review

#1370 Simplify command ACK
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
Labels: no-news-is-good-news, quick-review

#1372 Bump version for 2.8.0a0 alpha testing release
  compute_endpoint/globus_compute_endpoint/version.py
  compute_endpoint/setup.py
  compute_sdk/globus_compute_sdk/version.py
Labels: no-news-is-good-news, quick-review

#1374 Upgrade pip before running safety checks
  .github/workflows/ci.yaml
Labels: no-news-is-good-news
