Repository globus/globus-compute, pull requests merged in 2023-09, with the labels that each got.

#1288 Also block macos from configuring multi-tenant endpoints
  compute_endpoint/globus_compute_endpoint/cli.py
Labels: no-news-is-good-news, quick-review

#1290 Two forgotten files to endpoint packaging
  compute_endpoint/MANIFEST.in
Labels: no-news-is-good-news, quick-review

#1292 Upgrade requests
  changelog.d/20230907_152826_kevin_upgrade_requests.rst
  compute_endpoint/setup.py
  compute_sdk/setup.py
Labels: quick-review

#1299 Update mypy
  compute_endpoint/tox.ini
  compute_sdk/tox.ini
Labels: no-news-is-good-news, quick-review

#1300 Remove noisy log during test
  compute_endpoint/tests/unit/test_cli_behavior.py
Labels: no-news-is-good-news, quick-review

#1301 Refactor engine test fixtures
  compute_endpoint/tests/conftest.py
  compute_endpoint/tests/unit/test_engines.py
  compute_endpoint/tests/unit/test_status_reporting.py
Labels: no-news-is-good-news, quick-review

#1302 Add Engine .shutdown() expected interface
  changelog.d/20230918_120556_kevin_address_gc_engine_shutdown_bug.rst
  compute_endpoint/globus_compute_endpoint/engines/base.py
  compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
  compute_endpoint/globus_compute_endpoint/engines/high_throughput/engine.py
  compute_endpoint/globus_compute_endpoint/engines/process_pool.py
  compute_endpoint/globus_compute_endpoint/engines/thread_pool.py
  compute_endpoint/tests/conftest.py
Labels: quick-review

#1303 Remove unused metadata entries
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
  compute_endpoint/tests/unit/test_endpoint_unit.py
Labels: no-news-is-good-news, quick-review

#1309 Address flaky test
  compute_endpoint/tests/unit/test_command_queue_subscriber.py
Labels: no-news-is-good-news, quick-review

#1307 Show 5 slowest test durations
  compute_endpoint/tox.ini
  compute_sdk/tox.ini
Labels: no-news-is-good-news, quick-review

#1308 Address formatting on QuickStart page
  docs/quickstart.rst
Labels: no-news-is-good-news, quick-review

#1310 Show precise import error if debugging
  compute_endpoint/globus_compute_endpoint/cli.py
Labels: no-news-is-good-news, quick-review

#1311 Allow passing in MT creds on stdin
  compute_endpoint/globus_compute_endpoint/cli.py
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
Labels: no-news-is-good-news, quick-review

#1313 Update prod AMQP service host to new domain
  compute_sdk/globus_compute_sdk/sdk/_environments.py
  compute_sdk/tests/unit/test_environment_lookups.py
Labels: no-news-is-good-news

#1314 Release/v2.4.0a0
  changelog.d/20230822_132114_LeiGlobus_report_worker_sdk_version_sc_25606.rst
  changelog.d/20230828_165626_LeiGlobus_unknown_task_id_sc_24535.rst
  changelog.d/20230830_153211_30907815+rjmello_self_diagnostic_env.rst
  changelog.d/20230906_131715_30907815+rjmello_auth_errors.rst
  changelog.d/20230907_141555_30907815+rjmello_self_diag_ssl_conn.rst
  changelog.d/20230907_152826_kevin_upgrade_requests.rst
  changelog.d/20230911_113153_30907815+rjmello_HEAD.rst
  changelog.d/20230913_094159_30907815+rjmello.rst
  changelog.d/20230918_120556_kevin_address_gc_engine_shutdown_bug.rst
  changelog.d/20230918_204250_30907815+rjmello_serialize_config.rst
  compute_endpoint/globus_compute_endpoint/version.py
  compute_endpoint/setup.py
  compute_funcx/endpoint/funcx_endpoint/version.py
  compute_funcx/endpoint/setup.py
  compute_funcx/sdk/funcx/version.py
  compute_funcx/sdk/setup.py
  compute_sdk/globus_compute_sdk/version.py
  docs/changelog.rst
Labels: no-news-is-good-news, quick-review

#1316 Bump version number for release
  compute_endpoint/globus_compute_endpoint/version.py
  compute_endpoint/setup.py
  compute_funcx/endpoint/funcx_endpoint/version.py
  compute_funcx/endpoint/setup.py
  compute_funcx/sdk/funcx/version.py
  compute_funcx/sdk/setup.py
  compute_sdk/globus_compute_sdk/version.py
Labels: no-news-is-good-news, quick-review
