Repository globus/globus-compute, pull requests merged in 2023-04, with the labels that each got.

#1081 Bump versions for release
  changelog.d/20230327_121223_chris_remove_sdk_support_for_function_search.rst
  changelog.d/20230330_005243_kevin_max_idle_s_after_work.rst
  changelog.d/20230403_125849_kevin_broken_endpoint_for_new_users.rst
  docs/changelog.rst
  funcx_endpoint/funcx_endpoint/version.py
  funcx_sdk/funcx/version.py
Labels: no-news-is-good-news, quick-review

#1085 Fix release version check
  release.sh
Labels: no-news-is-good-news, quick-review

#1082 Change to address by interface for midway config examples.
  docs/configs/midway.py
  docs/configs/midway_singularity.py
Labels: Documentation, no-news-is-good-news

#1088 Clean up signal handlers
  compute_endpoint/tests/conftest.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_interchange.py
  compute_endpoint/tests/unit/test_endpointinterchange.py
  compute_endpoint/tests/unit/test_endpointmanager_unit.py
  compute_endpoint/tests/unit/test_highthroughputinterchange.py
  compute_endpoint/tests/unit/test_worker.py
Labels: no-news-is-good-news, quick-review

#1091 Removing obsolete classvar
  compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
Labels: no-news-is-good-news

#1096 Remove unused variable
  compute_endpoint/globus_compute_endpoint/executors/high_throughput/worker.py
Labels: no-news-is-good-news, quick-review

#1097 Fix typo in class name from funcx_endpoint
  compute_funcx/endpoint/funcx_endpoint/executors/high_throughput/funcx_manager.py
Labels: no-news-is-good-news, quick-review

#1098 Undo rebrand-lost change
  helm/boot.sh
Labels: no-news-is-good-news, quick-review

#1099 Add `allowlist_externals` in addition to `whitelist_externals` in `tox.ini`s
  compute_endpoint/tox.ini
  compute_funcx/endpoint/tox.ini
  compute_funcx/sdk/tox.ini
  compute_sdk/tox.ini
Labels: no-news-is-good-news

#1102 Fix typo in upgrade doc
  docs/funcx_upgrade.rst
Labels: Documentation, no-news-is-good-news, quick-review

#1103 Update HTEX .start() with add'l params
  compute_endpoint/globus_compute_endpoint/executors/high_throughput/executor.py
Labels: no-news-is-good-news, quick-review

#1092 Updating parsl req to 2023.03.27
  compute_endpoint/setup.py
Labels: no-news-is-good-news

#1104 EPInterchange uses exactly one executor
  compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_interchange.py
  compute_endpoint/tests/integration/endpoint/executors/mock_executors.py
  compute_endpoint/tests/unit/test_endpointinterchange.py
Labels: no-news-is-good-news, quick-review

#1105 Refactor to queue.Queue from mp.Queue
  compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
  compute_endpoint/globus_compute_endpoint/executors/high_throughput/executor.py
  compute_endpoint/tests/unit/test_endpointinterchange.py
Labels: no-news-is-good-news, quick-review

#1108 Add missing __init__.py files
  compute_funcx/endpoint/funcx_endpoint/endpoint/__init__.py
  compute_funcx/endpoint/funcx_endpoint/endpoint/utils/__init__.py
  compute_funcx/endpoint/funcx_endpoint/executors/high_throughput/__init__.py
  compute_funcx/sdk/funcx/sdk/__init__.py
Labels: bug, no-news-is-good-news, quick-review

#1111 Move display_name to top-level
  helm/funcx_endpoint/templates/endpoint-instance-config.yaml
Labels: no-news-is-good-news, quick-review

#1112 Update endpoint helm chart
  helm/funcx_endpoint/Chart.yaml
Labels: no-news-is-good-news, quick-review

#1110 Update wording for funcx-endpoint version check
  compute_endpoint/globus_compute_endpoint/cli.py
Labels: no-news-is-good-news, quick-review

#1114 Add required fields to final EP status report
  changelog.d/20230420_045259_30907815+rjmello.rst
  compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
Labels: bug, quick-review

#1115 Mild test refactor
  compute_endpoint/tests/integration/endpoint/endpoint/test_interchange.py
Labels: no-news-is-good-news, quick-review

#1116 Fix recently introduced bug
  compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_interchange.py
Labels: no-news-is-good-news, quick-review

#1113 action provider schema input output update
  docs/actionprovider.rst
Labels: Documentation, no-news-is-good-news

#1118 Update chart for endopint
  helm/funcx_endpoint/Chart.yaml
Labels: no-news-is-good-news, quick-review

#1121 remove GC_TASK timeout
  Dockerfile-endpoint
  reinstall.sh
Labels: no-news-is-good-news

#1126 change capitalization for link in upgrade doc
  docs/funcx_upgrade.rst
Labels: no-news-is-good-news, quick-review

#1127 Reduce some unnecessary log churn
  compute_endpoint/globus_compute_endpoint/executors/high_throughput/interchange.py
  compute_endpoint/globus_compute_endpoint/providers/kubernetes/kube.py
  compute_endpoint/globus_compute_endpoint/strategies/kube_simple.py
Labels: no-news-is-good-news, quick-review

#1128 Add bashrc to Docker image
  Dockerfile-endpoint
  helm/bashrc
Labels: no-news-is-good-news, quick-review

#1131 add import as for FuncXClient and FuncXExecutor
  compute_funcx/sdk/funcx/sdk/client.py
  compute_funcx/sdk/funcx/sdk/executor.py
  docs/changelog_funcx.rst
Labels: no-news-is-good-news, quick-review

#1134 Pass GC_TASK_TIMEOUT to instantianted pod
  compute_endpoint/globus_compute_endpoint/providers/kubernetes/kube.py
Labels: no-news-is-good-news, quick-review

#1135 Teach interchange to send bite-sized updates
  compute_endpoint/globus_compute_endpoint/executors/high_throughput/interchange.py
Labels: no-news-is-good-news, quick-review

#1136 Reduce some log noise
  compute_endpoint/globus_compute_endpoint/executors/high_throughput/container_sched.py
  compute_endpoint/globus_compute_endpoint/executors/high_throughput/interchange.py
  compute_endpoint/globus_compute_endpoint/executors/high_throughput/manager.py
  compute_endpoint/globus_compute_endpoint/executors/high_throughput/worker_map.py
Labels: no-news-is-good-news, quick-review
