Repository globus/globus-compute, pull requests merged in 2023-05, with the labels that each got.

#1139 bump versions for 2.0.2a0 alpha release
  changelog.d/20230421_103504_LeiGlobus_update_globus_urls_sc_23455.rst
  changelog.d/20230421_111659_kevin_address_concurrent_data_structure_modification.rst
  compute_endpoint/globus_compute_endpoint/version.py
  compute_endpoint/setup.py
  compute_funcx/endpoint/funcx_endpoint/version.py
  compute_funcx/endpoint/setup.py
  compute_funcx/sdk/funcx/version.py
  compute_funcx/sdk/setup.py
  compute_sdk/globus_compute_sdk/version.py
  docs/changelog.rst
  docs/changelog_funcx.rst
Labels: no-news-is-good-news, quick-review

#1145 Send EPStatusReport even if no outstanding tasks
  compute_endpoint/globus_compute_endpoint/executors/high_throughput/interchange.py
Labels: no-news-is-good-news, quick-review

#1147 Remove binder badge and replace quickstart reference
  README.rst
  docs/quickstart.rst
Labels: Documentation, no-news-is-good-news

#1148 Remove launch tag on README
  README.rst
Labels: bug, no-news-is-good-news

#1146 Use `global_state` instead of `ep_status_report` when constructing `EPStatusReport` objects
  compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
  compute_endpoint/globus_compute_endpoint/engines/process_pool.py
  compute_endpoint/globus_compute_endpoint/engines/thread_pool.py
Labels: no-news-is-good-news

#1150 config serialization test
  compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint.py
  compute_endpoint/tests/unit/test_endpoint_unit.py
Labels: no-news-is-good-news, quick-review

#1155 Add user-facing EP name validation
  changelog.d/20230523_125601_kevin_no_spaces_in_ep_name.rst
  compute_endpoint/globus_compute_endpoint/cli.py
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
  compute_endpoint/tests/unit/test_cli_behavior.py
  compute_endpoint/tests/unit/test_endpoint_unit.py
Labels: quick-review

#1154 Update Polaris example config
  docs/configs/polaris.py
Labels: no-news-is-good-news

#1156 Bump versions for release
  changelog.d/20230503_101434_yadudoc1729_unfork_htex_2.rst
  changelog.d/20230523_125601_kevin_no_spaces_in_ep_name.rst
  compute_endpoint/globus_compute_endpoint/version.py
  compute_endpoint/setup.py
  compute_funcx/endpoint/funcx_endpoint/version.py
  compute_funcx/endpoint/setup.py
  compute_funcx/sdk/funcx/version.py
  compute_funcx/sdk/setup.py
  compute_sdk/globus_compute_sdk/version.py
  docs/changelog.rst
  docs/changelog_funcx.rst
Labels: no-news-is-good-news, quick-review

#1158 Remove command to install pyzmq in EP Dockerfile
  Dockerfile-endpoint
Labels: no-news-is-good-news, quick-review

#1161 Temporarily send entry_point on function registration
  compute_sdk/globus_compute_sdk/sdk/web_client.py
Labels: no-news-is-good-news, quick-review

#1162 Revert "Temporarily send entry_point on function registration"
  compute_sdk/globus_compute_sdk/sdk/web_client.py
Labels: bug, no-news-is-good-news, quick-review
