Repository globus/globus-compute, pull requests merged in 2023-06, with the labels that each got.

#1152 change language for endpoint name errors and disallow UUID
  changelog.d/20230518_130845_LeiGlobus_endpoint_uuid_argument_sc_24353.rst
  compute_endpoint/globus_compute_endpoint/cli.py
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
  compute_endpoint/tests/unit/test_cli_behavior.py
Labels: quick-review

#1166 Add missing pyyaml dependency
  compute_endpoint/setup.py
Labels: bug, no-news-is-good-news, quick-review

#1173 Adjust indent in Blue Waters example config
  docs/configs/bluewaters.yaml
Labels: Documentation, no-news-is-good-news, quick-review

#1176 Rename `executor` to `engine` in YAML config
  compute_endpoint/globus_compute_endpoint/endpoint/config/default_config.yaml
  compute_endpoint/globus_compute_endpoint/endpoint/config/model.py
  compute_endpoint/tests/unit/test_cli_behavior.py
  compute_endpoint/tests/unit/test_endpoint_unit.py
  compute_endpoint/tests/unit/test_endpointmanager_unit.py
  docs/configs/bebop.yaml
  docs/configs/bluewaters.yaml
  docs/configs/cooley.yaml
  docs/configs/cori.yaml
  docs/configs/frontera.yaml
  docs/configs/kube.yaml
  docs/configs/midway.yaml
  docs/configs/midway_singularity.yaml
  docs/configs/perlmutter.yaml
  docs/configs/polaris.yaml
  docs/configs/theta.yaml
  docs/configs/theta_singularity.yaml
  docs/configs/uchicago_ai_cluster.yaml
  docs/configs/worker_pinning.yaml
  helm/funcx_endpoint/templates/endpoint-instance-config.yaml
  smoke_tests/tests/sh/test_endpoint.sh
Labels: no-news-is-good-news

#1184 Globuscs environments
  compute_endpoint/globus_compute_endpoint/version.py
  compute_endpoint/setup.py
  compute_funcx/endpoint/funcx_endpoint/version.py
  compute_funcx/endpoint/setup.py
  compute_funcx/sdk/funcx/version.py
  compute_funcx/sdk/setup.py
  compute_sdk/globus_compute_sdk/sdk/_environments.py
  compute_sdk/globus_compute_sdk/version.py
  compute_sdk/tests/unit/test_environment_lookups.py
  docs/changelog.rst
  docs/changelog_funcx.rst
Labels: no-news-is-good-news, quick-review

#1183 Remove unixtime prefix
  compute_endpoint/globus_compute_endpoint/logging_config.py
Labels: no-news-is-good-news, quick-review

#1185 Change funcx.org to compute.globus.org in docs
  docs/endpoints.rst
Labels: Documentation, no-news-is-good-news

#1186 Add default_config.yaml to MANIFEST.in
  compute_endpoint/MANIFEST.in
Labels: bug, no-news-is-good-news

#1189 Fix formatting in changelog
  docs/changelog.rst
  docs/changelog_funcx.rst
Labels: no-news-is-good-news, quick-review

#1190 Update the polaris example config
  docs/configs/polaris.yaml
Labels: Documentation, no-news-is-good-news

#1191 Replace single quotes in yaml configs
  docs/changelog_funcx.rst
  docs/configs/bebop.yaml
  docs/configs/bluewaters.yaml
  docs/configs/cooley.yaml
  docs/configs/cori.yaml
  docs/configs/frontera.yaml
  docs/configs/kube.yaml
  docs/configs/midway.yaml
  docs/configs/midway_singularity.yaml
  docs/configs/perlmutter.yaml
  docs/configs/theta.yaml
  docs/configs/theta_singularity.yaml
  docs/configs/worker_pinning.yaml
Labels: no-news-is-good-news, quick-review

#1192 Fix duplicate validator name
  compute_endpoint/globus_compute_endpoint/endpoint/config/model.py
Labels: bug, no-news-is-good-news, quick-review

#1194 Add changelog for YAML config bugfix
  changelog.d/20230622_214149_30907815+rjmello_bugfix_strategy.rst
Labels: Documentation, quick-review

#1201 Add Bridges-2 example config
  docs/_static/images/bridges-2.png
  docs/configs/bridges-2.yaml
  docs/configuring.rst
Labels: no-news-is-good-news, quick-review

#1200 Specify API version in each request
  compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint.py
  compute_sdk/globus_compute_sdk/sdk/_environments.py
  compute_sdk/globus_compute_sdk/sdk/client.py
  compute_sdk/globus_compute_sdk/sdk/web_client.py
  compute_sdk/tests/unit/test_client.py
  compute_sdk/tests/unit/test_environment_lookups.py
  compute_sdk/tests/unit/test_web_client.py
Labels: no-news-is-good-news
