Repository globus/globus-compute, pull requests merged in 2023-01, with the labels that each got.

#997 Add a small amount of typing
  funcx_endpoint/funcx_endpoint/executors/high_throughput/container_sched.py
  funcx_endpoint/funcx_endpoint/executors/high_throughput/funcx_manager.py
  funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
  funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange_task_dispatch.py
  funcx_endpoint/funcx_endpoint/executors/high_throughput/worker_map.py
  funcx_endpoint/funcx_endpoint/logging_config.py
  funcx_endpoint/funcx_endpoint/strategies/kube_simple.py
  funcx_endpoint/tests/integration/funcx_endpoint/conftest.py
Labels: no-news-is-good-news

#998 Do not pre-emptively test auth status
  funcx_sdk/funcx/sdk/login_manager/login_flow.py
  funcx_sdk/funcx/sdk/login_manager/manager.py
  funcx_sdk/tests/unit/test_login_manager.py
Labels: no-news-is-good-news, quick-review

#1000 Correct errant test
  funcx_sdk/tests/unit/test_login_manager.py
Labels: no-news-is-good-news, quick-review

#1001 Minor refactor
  funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
  funcx_endpoint/tests/integration/funcx_endpoint/endpoint/test_endpoint_manager.py
Labels: no-news-is-good-news, quick-review

#1002 Another minor "to pathlib" refactor
  funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
  funcx_endpoint/tests/unit/test_endpoint_unit.py
Labels: no-news-is-good-news, quick-review

#1004 Interchange cleanup
  funcx_endpoint/funcx_endpoint/executors/high_throughput/executor.py
Labels: no-news-is-good-news, quick-review

#1005 Doc update to clarify that the binder link is a hosted jupyter notebook.
  docs/quickstart.rst
Labels: no-news-is-good-news, quick-review

#1006 Fine-tune endpoint quiesce interaction
  funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
  funcx_endpoint/funcx_endpoint/endpoint/interchange.py
  funcx_endpoint/funcx_endpoint/endpoint/register_endpoint.py
  funcx_endpoint/funcx_endpoint/logging_config.py
  funcx_endpoint/tests/integration/funcx_endpoint/endpoint/test_interchange.py
  funcx_endpoint/tests/integration/funcx_endpoint/endpoint/test_interchange_with_rabbit.py
  funcx_endpoint/tests/integration/funcx_endpoint/endpoint/test_register_ep.py
  funcx_endpoint/tests/unit/test_endpoint_unit.py
  funcx_endpoint/tests/unit/test_endpointinterchange.py
  funcx_endpoint/tests/unit/test_register_endpoint.py
Labels: no-news-is-good-news

#1008 Remove unused constants
  funcx_endpoint/funcx_endpoint/endpoint/interchange.py
  funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
Labels: no-news-is-good-news, quick-review

#1007 Minor documentation and log changes
  funcx_endpoint/funcx_endpoint/endpoint/interchange.py
Labels: no-news-is-good-news, quick-review

#1009 Remove unnecessary use of EP name
  funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
  funcx_endpoint/funcx_endpoint/endpoint/interchange.py
  funcx_endpoint/funcx_endpoint/endpoint/result_store.py
  funcx_endpoint/tests/integration/funcx_endpoint/endpoint/test_endpoint_manager.py
Labels: no-news-is-good-news, quick-review

#1010 Shutdown after N failures
  changelog.d/20230113_121808_kevin_fail_count_then_bail.rst
  funcx_endpoint/funcx_endpoint/endpoint/interchange.py
  funcx_endpoint/tests/unit/test_endpointinterchange.py
Labels: quick-review

#1011 Minor refactor to use pathlib
  funcx_endpoint/funcx_endpoint/cli.py
Labels: no-news-is-good-news, quick-review

#1012 Bump versions and changelog for release
  changelog.d/20220803_120705_ben_container_service.rst
  changelog.d/20221208_132701_LeiGlobus_remove_funcx_errors_use.rst
  changelog.d/20221212_155851_30907815+rjmello_stop_ep.rst
  changelog.d/20221216_103757_30907815+rjmello_invalid_grant.rst
  changelog.d/20230106_132001_yadudoc1729_limit_interface_binding.rst
  changelog.d/20230113_121808_kevin_fail_count_then_bail.rst
  docs/changelog.rst
  funcx_endpoint/funcx_endpoint/version.py
  funcx_endpoint/setup.py
  funcx_sdk/funcx/version.py
Labels: no-news-is-good-news, quick-review

#1013 Include the -k doe flag for polaris
  docs/configs/polaris.py
Labels: Documentation, no-news-is-good-news, quick-review

#1014 funcx error fix
  funcx_sdk/funcx/errors/error_types.py
  funcx_sdk/funcx/sdk/client.py
  funcx_sdk/funcx/sdk/executor.py
  funcx_sdk/tests/unit/test_client.py
Labels: no-news-is-good-news, quick-review

#1015 Add methods for retrieving endpoint metadata
  funcx_sdk/funcx/sdk/client.py
  funcx_sdk/funcx/sdk/web_client.py
Labels: no-news-is-good-news

#1017 Fix safety check
  .github/workflows/ci.yaml
Labels: no-news-is-good-news, quick-review

#1016 Bump versions for alpha release
  funcx_endpoint/funcx_endpoint/version.py
  funcx_sdk/funcx/version.py
Labels: no-news-is-good-news, quick-review

#1019 Robustify task processing
  funcx_endpoint/funcx_endpoint/endpoint/interchange.py
  funcx_endpoint/funcx_endpoint/endpoint/messages_compat.py
  funcx_endpoint/tests/integration/funcx_endpoint/endpoint/test_interchange.py
  funcx_endpoint/tests/integration/funcx_endpoint/endpoint/test_messages_compat.py
Labels: no-news-is-good-news, quick-review

#1022 Remove use of FuncXClient from interchanges
  funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
  funcx_endpoint/funcx_endpoint/endpoint/interchange.py
  funcx_endpoint/funcx_endpoint/endpoint/messages_compat.py
  funcx_endpoint/funcx_endpoint/executors/high_throughput/executor.py
  funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
  funcx_endpoint/setup.py
  funcx_endpoint/tests/integration/funcx_endpoint/endpoint/test_interchange.py
  funcx_endpoint/tests/integration/funcx_endpoint/endpoint/test_interchange_with_rabbit.py
  funcx_endpoint/tests/integration/funcx_endpoint/endpoint/test_messages_compat.py
  funcx_endpoint/tests/unit/test_endpointinterchange.py
  funcx_sdk/setup.py
Labels: no-news-is-good-news, quick-review

#1023 Completely remove Endpoint.name
  funcx_endpoint/funcx_endpoint/cli.py
  funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
  funcx_endpoint/tests/integration/funcx_endpoint/endpoint/test_endpoint.py
  funcx_endpoint/tests/integration/funcx_endpoint/endpoint/test_endpoint_manager.py
  funcx_endpoint/tests/integration/funcx_endpoint/endpoint/test_interchange.py
  funcx_endpoint/tests/unit/test_endpoint_unit.py
Labels: no-news-is-good-news, quick-review

#1024 More easily discern EP processes in process table
  funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
  funcx_endpoint/setup.py
  funcx_endpoint/tests/unit/test_endpoint_unit.py
Labels: no-news-is-good-news, quick-review

#1021 Auto-shutdown FuncXExecutor objects at script end
  changelog.d/20230124_175331_kevin_readd_atexit_handler_to_fxexecutor.rst
  funcx_sdk/funcx/sdk/executor.py
  funcx_sdk/tests/integration/test_executor_int.py
  funcx_sdk/tests/unit/test_executor.py
Labels: quick-review

#1025 Teach FuncXExecutor to use container_id natively
  changelog.d/20230126_125531_kevin_reteach_executor_how_to_specify_containers.rst
  funcx_sdk/funcx/sdk/executor.py
  funcx_sdk/tests/unit/test_executor.py
Labels: quick-review

#1030 Whoami PR comments
  changelog.d/20230126_135722_LeiGlobus_whoami_sc_21319.rst
  funcx_sdk/funcx/sdk/login_manager/whoami.py
  funcx_sdk/funcx/sdk/utils/printing.py
  funcx_sdk/tests/unit/test_whoami.py
Labels: no-news-is-good-news, quick-review
