Repository globus/globus-compute, pull requests merged in 2023-02, with the labels that each got.

#1026 Teach endpoint to read credentials via stdin
  funcx_endpoint/funcx_endpoint/cli.py
  funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
  funcx_endpoint/tests/integration/funcx_endpoint/endpoint/test_endpoint.py
  funcx_endpoint/tests/integration/funcx_endpoint/endpoint/test_endpoint_manager.py
  funcx_endpoint/tests/unit/test_cli_behavior.py
  funcx_endpoint/tests/unit/test_endpoint_unit.py
Labels: no-news-is-good-news, quick-review

#1032 Correct data structure traversal
  changelog.d/20230202_002915_kevin_htex_interchange_bad_manager_iteration_fix.rst
  funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
Labels: bug, no-news-is-good-news, quick-review

#1033 Bump versions and changelog for (bugfix) release
  changelog.d/20230202_002915_kevin_htex_interchange_bad_manager_iteration_fix.rst
  docs/changelog.rst
  funcx_endpoint/funcx_endpoint/version.py
  funcx_sdk/funcx/version.py
Labels: quick-review

#1036 Delete README.rst in endpoint dir
  funcx_endpoint/funcx_endpoint/README.rst
Labels: no-news-is-good-news, quick-review

#1038 Reduce log noise from JobStatus updates
  funcx_endpoint/funcx_endpoint/strategies/simple.py
Labels: no-news-is-good-news, quick-review

#1040 Implement flag to maintain process tree
  funcx_endpoint/funcx_endpoint/cli.py
  funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
  funcx_endpoint/funcx_endpoint/endpoint/interchange.py
  funcx_endpoint/tests/integration/funcx_endpoint/endpoint/test_interchange.py
  funcx_endpoint/tests/unit/test_cli_behavior.py
Labels: no-news-is-good-news, quick-review

#1042 Add logic in case error reason non existent
  funcx_sdk/funcx/sdk/client.py
  funcx_sdk/tests/unit/test_client.py
Labels: no-news-is-good-news, quick-review

#1043 Remove dead status_message handling code
  funcx_endpoint/funcx_endpoint/executors/high_throughput/executor.py
  funcx_endpoint/funcx_endpoint/executors/high_throughput/interchange.py
Labels: no-news-is-good-news, quick-review

#1039 Add stdin to the daemon context
  funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
Labels: bug, no-news-is-good-news

#1048 Also include config.py in umask handling
  funcx_endpoint/funcx_endpoint/endpoint/endpoint.py
Labels: no-news-is-good-news, quick-review
