Repository globus/globus-compute, pull requests merged in 2023-12, with the labels that each got.

#1382 Fix smoke test
  smoke_tests/tests/test_running_functions.py
Labels: no-news-is-good-news, quick-review

#1384 Remove detritus from CI image
  .github/workflows/ci.yaml
Labels: no-news-is-good-news, quick-review

#1380 Give some helpful info on a suspected serialization error
  compute_sdk/globus_compute_sdk/errors/error_types.py
  compute_sdk/tests/unit/test_error_types.py
Labels: no-news-is-good-news, quick-review

#1385 Update to parsl 2023.12.4
  changelog.d/20231212_095641_yadudoc1729_update_to_parsl_2023_12_4.rst
  compute_endpoint/globus_compute_endpoint/strategies/simple.py
  compute_endpoint/setup.py
Labels: quick-review

#1386 Be precise about repr() in exceptions
  compute_sdk/globus_compute_sdk/sdk/executor.py
Labels: no-news-is-good-news, quick-review

#1387 Remove unused `_status_report` method
  compute_endpoint/globus_compute_endpoint/engines/base.py
Labels: no-news-is-good-news, quick-review

#1388 Be explicit about use of `repr()`
  compute_sdk/globus_compute_sdk/sdk/executor.py
Labels: no-news-is-good-news, quick-review

#1391 Minor NFC change to test_cli codes
  compute_endpoint/tests/unit/test_cli_behavior.py
Labels: no-news-is-good-news, quick-review

#1389 Add warning for stuck thread and early stop
  compute_sdk/globus_compute_sdk/sdk/executor.py
  compute_sdk/tests/unit/test_executor.py
Labels: no-news-is-good-news, quick-review

#1392 Fix flubbed default user template
  compute_endpoint/globus_compute_endpoint/cli.py
  compute_endpoint/globus_compute_endpoint/endpoint/config/user_config_schema.json
  compute_endpoint/globus_compute_endpoint/endpoint/config/user_config_template.yaml
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint_manager.py
  compute_endpoint/tests/unit/test_cli_behavior.py
  compute_endpoint/tests/unit/test_endpoint_unit.py
Labels: no-news-is-good-news

#1390 Bump versions and collect changelog for release
  changelog.d/20231031_230517_yadudoc1729_task_retries_1.rst
  changelog.d/20231204_155243_chris_remove_funcx_client.rst
  changelog.d/20231212_095641_yadudoc1729_update_to_parsl_2023_12_4.rst
  compute_endpoint/globus_compute_endpoint/version.py
  compute_endpoint/setup.py
  compute_sdk/globus_compute_sdk/version.py
  docs/changelog.rst
Labels: no-news-is-good-news

#1394 Be more transparent with identity mapping errors
  compute_endpoint/globus_compute_endpoint/endpoint/identity_mapper.py
  compute_endpoint/tests/unit/test_identity_mapper.py
Labels: no-news-is-good-news, quick-review

#1397 Pin Parsl to 2023.12.18
  changelog.d/20231219_144502_30907815+rjmello.rst
  compute_endpoint/setup.py
Labels: quick-review
