Repository globus/globus-compute, pull requests merged in 2024-01, with the labels that each got.

#1400 Set quiesce event when task RMQ channel closes
  changelog.d/20240102_141658_30907815+rjmello_HEAD.rst
  compute_endpoint/globus_compute_endpoint/endpoint/rabbit_mq/task_queue_subscriber.py
  compute_endpoint/tests/integration/test_rabbit_mq/test_task_q.py
Labels: bug

#1401 Bump version for releasing 2.10.0 Jan 3 2024
  changelog.d/20231216_131520_kurtmckee_fix_daily_workflow.rst
  changelog.d/20231219_144502_30907815+rjmello.rst
  changelog.d/20240102_141658_30907815+rjmello_HEAD.rst
  compute_endpoint/globus_compute_endpoint/version.py
  compute_endpoint/setup.py
  compute_sdk/globus_compute_sdk/version.py
  docs/changelog.rst
Labels: quick-review

#1402 Update globus-identity-mapper
  compute_endpoint/setup.py
Labels: no-news-is-good-news, quick-review

#1403 Update mypy
  compute_endpoint/tox.ini
  compute_sdk/tox.ini
Labels: no-news-is-good-news, quick-review

#1404 Change default AMQP port for new endpoints to 443
  changelog.d/20240104_141408_chris_endpoint_default_443.rst
  compute_endpoint/globus_compute_endpoint/endpoint/config/default_config.yaml
  compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint.py
Labels: quick-review

#1406 Prefer sys.exit over exit
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
Labels: no-news-is-good-news, quick-review

#1407 Preparatory refactor
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
Labels: no-news-is-good-news, quick-review

#1408 Add 3 missing tests, fix missed assertions
  compute_endpoint/globus_compute_endpoint/endpoint/config/utils.py
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
  compute_endpoint/tests/unit/test_endpointmanager_unit.py
Labels: no-news-is-good-news

#1410 Update debug color palette
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
  compute_endpoint/globus_compute_endpoint/logging_config.py
Labels: no-news-is-good-news, quick-review

#1412 Update some old README.rst links
  README.rst
Labels: no-news-is-good-news, quick-review

#1413 Add non prod environments to smoke tests, replacing dev
  .github/workflows/daily.yaml
  smoke_tests/Makefile
  smoke_tests/README.md
  smoke_tests/tests/conftest.py
  smoke_tests/tests/test_version.py
Labels: no-news-is-good-news, quick-review

#1416 Implement CI timeouts
  .github/workflows/ci.yaml
Labels: no-news-is-good-news, quick-review

#1420 Fix docs build
  compute_sdk/setup.py
Labels: no-news-is-good-news, quick-review

#1418 set GLOBUS_SDK_ENVIRONMENT when make staging
  .github/workflows/daily.yaml
Labels: no-news-is-good-news, quick-review

#1415 Send UEP startup failure AMQP message
  compute_endpoint/globus_compute_endpoint/cli.py
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
  compute_endpoint/globus_compute_endpoint/endpoint/utils/__init__.py
  compute_endpoint/tests/unit/test_cli_behavior.py
  compute_endpoint/tests/unit/test_endpointmanager_unit.py
  compute_endpoint/tests/unit/test_utils.py
Labels: no-news-is-good-news

#1422 Address flaky test
  compute_sdk/tests/unit/test_executor.py
Labels: no-news-is-good-news, quick-review

#1425 Trying again to fix GLOBUS_SDK_ENVIRONMENT for smoke tests
  .github/workflows/daily.yaml
  smoke_tests/tests/conftest.py
Labels: no-news-is-good-news, quick-review

#1424 Remove unnecessary event
  compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_interchange.py
  compute_endpoint/tests/unit/test_endpointinterchange.py
Labels: no-news-is-good-news

#1405 Document endpoint AMQP port configuration
  docs/endpoints.rst
Labels: no-news-is-good-news

#1429 Fix broken fixture
  compute_sdk/tests/conftest.py
  compute_sdk/tests/unit/test_client.py
Labels: no-news-is-good-news, quick-review

#1430 Replace vestigial non-fixture instantions
  compute_sdk/tests/unit/test_client.py
Labels: no-news-is-good-news, quick-review

#1428 Add missing test for .reload_tasks
  compute_sdk/globus_compute_sdk/sdk/executor.py
  compute_sdk/tests/unit/test_executor.py
Labels: no-news-is-good-news, quick-review

#1438 Update parsl to 2024.01.22
  changelog.d/20240123_115035_kevin_update_parsl.rst
  compute_endpoint/setup.py
Labels: quick-review

#1439 Typo in changelog.
  changelog.d/20240123_115035_kevin_update_parsl.rst
Labels: no-news-is-good-news, quick-review

#1437 Update doc code blocks syntax highlighting
  docs/endpoints.rst
  docs/index.rst
Labels: no-news-is-good-news, quick-review

#1435 Adding reference docs for GlobusComputeEngine
  compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
  docs/reference/engine.rst
  docs/reference/index.rst
Labels: no-news-is-good-news

#1442 Bump versions for alpha release 2.12.0a0 for testing release
  compute_endpoint/globus_compute_endpoint/version.py
  compute_endpoint/setup.py
  compute_sdk/globus_compute_sdk/version.py
Labels: no-news-is-good-news, quick-review

#1441 Send endpoint_id to workers and back to SDK
  compute_endpoint/globus_compute_endpoint/engines/base.py
  compute_endpoint/globus_compute_endpoint/engines/helper.py
  compute_endpoint/globus_compute_endpoint/engines/high_throughput/engine.py
  compute_endpoint/tests/unit/test_execute_task.py
  compute_endpoint/tests/unit/test_worker.py
Labels: no-news-is-good-news, quick-review
