Repository globus/globus-compute, pull requests merged in 2024-10, with the labels that each got.

#1675 Release fix - Fix operator precedence in Jupyter checking
  compute_sdk/globus_compute_sdk/sdk/auth/globus_app.py
Labels: no-news-is-good-news, quick-review

#1677 Improve error message for errant func registration
  changelog.d/20241008_092953_kevin_improve_double_registration_error_message.rst
  compute_sdk/globus_compute_sdk/sdk/executor.py
  compute_sdk/tests/unit/test_executor.py
Labels: quick-review

#1678 increase smoke_test timeout for intermittent failure
  smoke_tests/tests/test_running_functions.py
Labels: no-news-is-good-news, quick-review

#1679 Add --verbose flag for the new self-diagnostic and put heading output behind it
  compute_sdk/globus_compute_sdk/sdk/diagnostic.py
  compute_sdk/tests/unit/test_diagnostic.py
Labels: no-news-is-good-news, quick-review

#1680 Use code-style formatting for link
  changelog.d/20241004_101450_rchard_set_default_max_workers.rst
  docs/changelog.rst
Labels: no-news-is-good-news, quick-review

#1681 Add short label to Kubernetes example config
  docs/endpoints/configs/kube.yaml
Labels: no-news-is-good-news, quick-review

#1683 Remove pipx --include-deps flag from docs
  docs/endpoints/single_user.rst
  docs/index.rst
  docs/quickstart.rst
Labels: no-news-is-good-news

#1682 add diagnostic ack message with file name
  compute_sdk/globus_compute_sdk/sdk/diagnostic.py
  compute_sdk/tests/unit/test_diagnostic.py
Labels: no-news-is-good-news, quick-review

#1685 Bump versions and changelog for release v2.29.0
  changelog.d/20240905_222235_LeiGlobus_sdk_self_diag_sc_33842.rst
  changelog.d/20240918_223810_kevin_bursty_rate_limit_executor_submit.rst
  changelog.d/20241004_101450_rchard_set_default_max_workers.rst
  changelog.d/20241008_092953_kevin_improve_double_registration_error_message.rst
  compute_endpoint/globus_compute_endpoint/version.py
  compute_endpoint/setup.py
  compute_sdk/globus_compute_sdk/version.py
  docs/changelog.rst
Labels: no-news-is-good-news

#1686 Fix AuthorizerLoginManager KeyError
  changelog.d/20241017_111821_30907815+rjmello_fix_authz_lm_auth_client.rst
  compute_sdk/globus_compute_sdk/sdk/login_manager/authorizer_login_manager.py
  compute_sdk/tests/unit/test_authorizer_login_manager.py
Labels: bug, quick-review

#1688 epmanager tests DRY refactor
  compute_endpoint/tests/unit/test_endpointmanager_unit.py
Labels: no-news-is-good-news, quick-review

#1690 Update initgroups thinking
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
  compute_endpoint/tests/unit/test_endpointmanager_unit.py
Labels: no-news-is-good-news, quick-review

#1692 Drop support for Python 3.8
  .github/workflows/ci.yaml
  README.rst
  changelog.d/20241023_194824_30907815+rjmello_HEAD.rst
  compute_endpoint/setup.py
  compute_endpoint/tox.ini
  compute_sdk/setup.py
  compute_sdk/tox.ini
  docs/quickstart.rst
Labels: quick-review

#1693 Bump parsl dependency to 2024.10.21
  changelog.d/20241023_153605_30907815+rjmello_bump_parsl_2024_10_21.rst
  compute_endpoint/setup.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_interchange_with_rabbit.py
  compute_endpoint/tests/integration/endpoint/executors/mock_executors.py
  compute_endpoint/tests/integration/endpoint/executors/test_mpiengine.py
Labels: quick-review

#1694 Bump versions for release v2.30.0
  changelog.d/20241015_192243_30907815+rjmello_HEAD.rst
  changelog.d/20241017_111821_30907815+rjmello_fix_authz_lm_auth_client.rst
  changelog.d/20241022_130023_kevin_batch_runtime_type_checking.rst
  changelog.d/20241023_153605_30907815+rjmello_bump_parsl_2024_10_21.rst
  changelog.d/20241023_194824_30907815+rjmello_HEAD.rst
  compute_endpoint/globus_compute_endpoint/version.py
  compute_endpoint/setup.py
  compute_sdk/globus_compute_sdk/version.py
  docs/changelog.rst
Labels: no-news-is-good-news, quick-review

#1695 Drop temporary fixes to Kubernetes example config
  docs/endpoints/configs/kube.yaml
Labels: no-news-is-good-news, quick-review

#1696 Skip errors when stdin closed if creds cached
  changelog.d/20241030_122237_30907815+rjmello_fix_globus_app_stdin_check.rst
  compute_sdk/globus_compute_sdk/sdk/auth/globus_app.py
  compute_sdk/tests/unit/auth/test_globus_app.py
Labels: bug
