Repository globus/globus-compute, pull requests merged in 2024-06, with the labels that each got.

#1581 Remove no-longer needed code
  compute_sdk/globus_compute_sdk/sdk/login_manager/tokenstore.py
  compute_sdk/tests/unit/test_login_manager.py
Labels: no-news-is-good-news, quick-review

#1582 Teach UEP configuration `debug` flag
  changelog.d/20240612_164858_kevin_enable_configurable_interchange_debug.rst
  compute_endpoint/globus_compute_endpoint/cli.py
  compute_endpoint/globus_compute_endpoint/endpoint/config/config.py
  compute_endpoint/globus_compute_endpoint/endpoint/config/model.py
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
  compute_endpoint/tests/unit/test_cli_behavior.py
Labels: quick-review

#1584 Log anonymous configuration in debug
  compute_endpoint/globus_compute_endpoint/cli.py
  compute_endpoint/tests/unit/test_cli_behavior.py
  docs/endpoints/multi_user.rst
Labels: no-news-is-good-news, quick-review

#1586 Reword default systemd service description
  compute_endpoint/globus_compute_endpoint/boot_persistence.py
Labels: no-news-is-good-news, quick-review

#1587 Add reference to `self-diagnostic` command in bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: no-news-is-good-news, quick-review

#1585 Warn if MEP user environment file is missing or empty
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
  compute_endpoint/tests/unit/test_endpointmanager_unit.py
Labels: no-news-is-good-news, quick-review

#1588 Enable GCEngine to support providers w/o a channel
  changelog.d/20240617_133114_30907815+rjmello_fix_gcengine_channel_check.rst
  compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
  compute_endpoint/tests/unit/test_engines.py
Labels: bug, quick-review

#1589 Bump versions and changelog for release v2.22.0
  changelog.d/20240423_142117_yadudoc1729_gce_working_dir.rst
  changelog.d/20240604_170320_chris_document_443_default_switch.rst
  changelog.d/20240612_164858_kevin_enable_configurable_interchange_debug.rst
  compute_endpoint/globus_compute_endpoint/version.py
  compute_endpoint/setup.py
  compute_sdk/globus_compute_sdk/version.py
  docs/changelog.rst
Labels: no-news-is-good-news

#1591 Add executable paths to self-diagnostic output
  changelog.d/20240622_114437_30907815+rjmello_add_bin_paths_to_self_diag.rst
  compute_endpoint/globus_compute_endpoint/self_diagnostic.py
  compute_endpoint/tests/unit/test_cli_behavior.py
Labels: quick-review

#1592 Rename local dev EP docker compose project
  local_dev/compose.yml
Labels: no-news-is-good-news, quick-review
