Repository globus/globus-compute, pull requests merged in 2024-11, with the labels that each got.

#1698 Update mypy
  compute_endpoint/tox.ini
  compute_sdk/tox.ini
Labels: no-news-is-good-news, quick-review

#1702 Clear test-induced warning
  compute_sdk/tests/unit/test_executor.py
Labels: no-news-is-good-news, quick-review

#1703 Fixup a flaky test setup
  compute_sdk/tests/unit/test_executor.py
Labels: no-news-is-good-news, quick-review

#1704 Don't needlessly instantiate GlobusComputeExecutor
  compute_endpoint/globus_compute_endpoint/endpoint/config/utils.py
  compute_endpoint/tests/unit/test_cli_behavior.py
Labels: no-news-is-good-news, quick-review

#1701 Reduce spurious DNS lookups in tests
  compute_endpoint/globus_compute_endpoint/engines/base.py
  compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
  compute_endpoint/tests/unit/test_boot_persistence.py
  compute_endpoint/tests/unit/test_cli_behavior.py
  compute_endpoint/tests/unit/test_endpoint_config.py
  compute_endpoint/tests/unit/test_endpoint_unit.py
  compute_endpoint/tests/unit/test_engines.py
Labels: no-news-is-good-news, quick-review

#1705 Mild executor fixture refactor
  compute_sdk/tests/unit/test_executor.py
Labels: no-news-is-good-news, quick-review

#1706 Fix flaky Executor test
  compute_sdk/tests/unit/test_executor.py
Labels: no-news-is-good-news, quick-review

#1708 Separate MultiUser configuration
  compute_endpoint/globus_compute_endpoint/boot_persistence.py
  compute_endpoint/globus_compute_endpoint/cli.py
  compute_endpoint/globus_compute_endpoint/endpoint/config/__init__.py
  compute_endpoint/globus_compute_endpoint/endpoint/config/config.py
  compute_endpoint/globus_compute_endpoint/endpoint/config/default_config.py
  compute_endpoint/globus_compute_endpoint/endpoint/config/model.py
  compute_endpoint/globus_compute_endpoint/endpoint/config/utils.py
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
  compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
  compute_endpoint/globus_compute_endpoint/engines/base.py
  compute_endpoint/globus_compute_endpoint/engines/high_throughput/interchange.py
  compute_endpoint/tests/conftest.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint_manager.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_interchange.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_interchange_with_rabbit.py
  compute_endpoint/tests/unit/conftest.py
  compute_endpoint/tests/unit/test_boot_persistence.py
  compute_endpoint/tests/unit/test_cli_behavior.py
  compute_endpoint/tests/unit/test_config_utils.py
  compute_endpoint/tests/unit/test_endpoint_config.py
  compute_endpoint/tests/unit/test_endpoint_unit.py
  compute_endpoint/tests/unit/test_endpointinterchange.py
  compute_endpoint/tests/unit/test_endpointmanager_unit.py
  compute_endpoint/tests/unit/test_engines.py
Labels: no-news-is-good-news

#1699 Disallow function and function_name
  changelog.d/20241101_153924_chris_function_name_code.rst
  compute_sdk/globus_compute_sdk/sdk/client.py
  compute_sdk/globus_compute_sdk/sdk/web_client.py
  compute_sdk/tests/unit/test_client.py
Labels: quick-review

#1711 Updating `GlobusComputeEngineBase` to use future annotations
  compute_endpoint/globus_compute_endpoint/engines/base.py
Labels: no-news-is-good-news, quick-review

#1714 Move result size check one level higher
  compute_endpoint/globus_compute_endpoint/engines/helper.py
Labels: no-news-is-good-news, quick-review

#1715 Remove unused HTEX tests
  compute_endpoint/tests/unit/test_htex.py
Labels: no-news-is-good-news, quick-review

#1717 Move test task kernel to utils
  compute_endpoint/tests/unit/test_execute_task.py
  compute_endpoint/tests/utils.py
Labels: no-news-is-good-news, quick-review

#1716 Remove test detritus
  compute_endpoint/tests/unit/test_htex.py
Labels: no-news-is-good-news, quick-review

#1719 Update execute_task signature
  compute_endpoint/globus_compute_endpoint/engines/helper.py
  compute_endpoint/tests/unit/conftest.py
  compute_endpoint/tests/unit/test_execute_task.py
  compute_endpoint/tests/unit/test_worker.py
Labels: no-news-is-good-news

#1721 Add general config documentation
  compute_endpoint/globus_compute_endpoint/endpoint/config/config.py
  docs/endpoints/config_reference.rst
  docs/endpoints/index.rst
Labels: no-news-is-good-news

#1712 Make test function readily-REPL-available
  compute_endpoint/tests/conftest.py
  compute_endpoint/tests/utils.py
Labels: no-news-is-good-news, quick-review

#1725 Tell Git to ignore custom compose files
  local_dev/.gitignore
  local_dev/compose.yaml
Labels: no-news-is-good-news, quick-review

#1728 Remove a fixture duplication
  compute_endpoint/tests/conftest.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint_manager.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_interchange_with_rabbit.py
  compute_endpoint/tests/unit/test_cli_behavior.py
  compute_endpoint/tests/unit/test_endpoint_unit.py
  compute_endpoint/tests/unit/test_endpointmanager_unit.py
Labels: no-news-is-good-news, quick-review

#1722 Remove code that checks if the user is in a TTY
  changelog.d/20241114_172127_chris_remove_tty_checks.rst
  compute_sdk/globus_compute_sdk/sdk/auth/globus_app.py
  compute_sdk/setup.py
  compute_sdk/tests/unit/auth/test_globus_app.py
Labels: no-news-is-good-news

#1732 Drop support for Python 3.13
  .github/workflows/ci.yaml
  changelog.d/20241111_160525_chris_new_pythons.rst
  compute_endpoint/tox.ini
  compute_sdk/tox.ini
Labels: no-news-is-good-news, quick-review

#1723 Document V3 of Compute Action Provider
  docs/actionprovider.rst
Labels: no-news-is-good-news

#1734 Bump parsl 11 25 and remove reference to removed method
  changelog.d/20241126_104747_LeiGlobus_bump_parsl_11_25.rst
  compute_endpoint/globus_compute_endpoint/engines/high_throughput/interchange.py
  compute_endpoint/setup.py
Labels: quick-review
