Repository globus/globus-compute, pull requests merged in 2024-09, with the labels that each got.

#1652 Remove vestigial test
  compute_endpoint/tests/unit/test_engines.py
Labels: no-news-is-good-news, quick-review

#1653 Fix bit-rotted delete endpoint test
  compute_endpoint/tests/unit/test_endpoint_unit.py
Labels: no-news-is-good-news, quick-review

#1655 Correct docs
  docs/executor.rst
  docs/mpi_functions.rst
  docs/shell_functions.rst
Labels: no-news-is-good-news, quick-review

#1657 Refactor selected tests to use fixtures
  compute_endpoint/tests/conftest.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_gcengine_shell_functions.py
  compute_endpoint/tests/integration/endpoint/executors/high_throughput/test_htex_regression.py
  compute_endpoint/tests/integration/endpoint/executors/test_gcengine_retries.py
  compute_endpoint/tests/integration/endpoint/executors/test_mpiengine.py
  compute_endpoint/tests/unit/test_engines.py
  compute_endpoint/tests/unit/test_execute_task.py
  compute_endpoint/tests/unit/test_htex.py
  compute_endpoint/tests/unit/test_worker.py
  compute_endpoint/tests/unit/test_working_dir.py
Labels: no-news-is-good-news

#1659 Allow `GLOBUS_COMPUTE_CLIENT_ID` env var alone
  changelog.d/20240905_180131_30907815+rjmello_allow_client_id_alone.rst
  compute_endpoint/tests/unit/test_cli_behavior.py
  compute_sdk/globus_compute_sdk/sdk/login_manager/client_login.py
  compute_sdk/tests/unit/test_login_manager.py
Labels: bug, quick-review

#1660 Update Parsl to 2024.9.9
  changelog.d/20240909_171516_kevin_update_parsl.rst
  compute_endpoint/setup.py
  compute_endpoint/tests/unit/test_engines.py
  compute_endpoint/tests/unit/test_status_reporting.py
Labels: quick-review

#1663 Implement JSON serialization strategy
  changelog.d/20240919_155327_chris_json_serializer.rst
  compute_sdk/globus_compute_sdk/errors/error_types.py
  compute_sdk/globus_compute_sdk/serialize/__init__.py
  compute_sdk/globus_compute_sdk/serialize/concretes.py
  docs/sdk.rst
Labels: quick-review

#1666 Remove obsolete Executor args
  compute_endpoint/tox.ini
  compute_sdk/globus_compute_sdk/sdk/executor.py
  compute_sdk/tests/unit/test_executor.py
  compute_sdk/tox.ini
Labels: no-news-is-good-news, quick-review

#1667 Remove forgotten debugging log
  compute_endpoint/globus_compute_endpoint/engines/process_pool.py
Labels: no-news-is-good-news, quick-review

#1664 Autobuild docs on file changes
  Makefile
  docs/autobuild.sh
Labels: no-news-is-good-news

#1668 Allow UEPs to create log files
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
  compute_endpoint/tests/unit/test_endpointmanager_unit.py
Labels: no-news-is-good-news, quick-review

#1670 Touchup changelog
  docs/changelog.rst
  docs/endpoints/multi_user.rst
Labels: no-news-is-good-news

#1671 Make UEP endpoint.log readable by default
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
  compute_endpoint/tests/unit/test_endpointmanager_unit.py
Labels: no-news-is-good-news, quick-review
