Repository globus/globus-compute, pull requests merged in 2024-07, with the labels that each got.

#1590 Update Endpoint to pass on resource_specification to GCEngine
  compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
  compute_endpoint/globus_compute_endpoint/engines/base.py
  compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
  compute_endpoint/globus_compute_endpoint/engines/high_throughput/engine.py
  compute_endpoint/globus_compute_endpoint/engines/process_pool.py
  compute_endpoint/globus_compute_endpoint/engines/thread_pool.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_gcengine_resource_spec.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_gcengine_strategy.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_interchange_with_rabbit.py
  compute_endpoint/tests/integration/endpoint/executors/high_throughput/test_htex_regression.py
  compute_endpoint/tests/integration/endpoint/executors/mock_executors.py
  compute_endpoint/tests/integration/endpoint/executors/test_gcengine_retries.py
  compute_endpoint/tests/unit/test_engines.py
  compute_endpoint/tests/unit/test_htex.py
  compute_endpoint/tests/utils.py
Labels: no-news-is-good-news

#1599 Update GCE to run tasks in `tasks_working_dir`
  changelog.d/20240702_104011_yadudoc1729_gce_run_tasks_in_working_dir.rst
  compute_endpoint/globus_compute_endpoint/engines/base.py
  compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
  compute_endpoint/tests/unit/test_working_dir.py
Labels: quick-review

#1601 Change version mismatch message, add logic to ignore Python micro # if desired
  compute_sdk/globus_compute_sdk/sdk/utils/__init__.py
  compute_sdk/tests/unit/test_client.py
  compute_sdk/tests/unit/test_util.py
Labels: no-news-is-good-news, quick-review

#1603 change check_news to also allow changelog itself
  .github/workflows/changelog.yml
Labels: no-news-is-good-news

#1602 Bump versions for prod release 2.23.0 2024-07-10
  changelog.d/20240410_130138_LeiGlobus_delete_remote_endpoint_sc_31206.rst
  changelog.d/20240617_133114_30907815+rjmello_fix_gcengine_channel_check.rst
  changelog.d/20240622_114437_30907815+rjmello_add_bin_paths_to_self_diag.rst
  changelog.d/20240628_090506_30907815+rjmello_bump_parsl_2024_06_10.rst
  changelog.d/20240702_104011_yadudoc1729_gce_run_tasks_in_working_dir.rst
  compute_endpoint/globus_compute_endpoint/version.py
  compute_endpoint/setup.py
  compute_sdk/globus_compute_sdk/version.py
  docs/changelog.rst
Labels: no-news-is-good-news, quick-review

#1605 Fix v2.23.0 changelog
  docs/changelog.rst
Labels: no-news-is-good-news, quick-review

#1606 Reformat env difference warning again and link to readthedocs
  compute_sdk/globus_compute_sdk/sdk/client.py
  compute_sdk/globus_compute_sdk/sdk/utils/__init__.py
  compute_sdk/tests/unit/test_client.py
  compute_sdk/tests/unit/test_util.py
  docs/sdk.rst
Labels: no-news-is-good-news

#1609 Use merge commit during release process
  RELEASING.md
Labels: Documentation, no-news-is-good-news, quick-review

#1611 Bump versions and changelog for release.
  changelog.d/20240612_140404_30907815+rjmello_pool_result_watchers_sc_33032.rst
  changelog.d/20240627_181028_chris_mep_config_user_runtime.rst
  changelog.d/20240702_175644_30907815+rjmello_exec_cmd_sc_34376.rst
  compute_endpoint/globus_compute_endpoint/version.py
  compute_endpoint/setup.py
  compute_sdk/globus_compute_sdk/version.py
  docs/changelog.rst
Labels: no-news-is-good-news

#1612 Merge adjacent `Changed` sections in changelog
  docs/changelog.rst
Labels: no-news-is-good-news, quick-review

#1614 Glob recursively in self diagnostic
  compute_endpoint/globus_compute_endpoint/self_diagnostic.py
  compute_endpoint/tests/unit/test_self_diagnostic.py
Labels: no-news-is-good-news

#1610 Disable MPI mode for `GlobusComputeEngine`
  compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
  compute_endpoint/globus_compute_endpoint/engines/globus_mpi.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_gcengine_resource_spec.py
  compute_endpoint/tests/integration/endpoint/executors/test_mpiengine.py
  compute_endpoint/tests/unit/test_engines.py
Labels: no-news-is-good-news
