Repository globus/globus-compute, pull requests merged in 2024-02, with the labels that each got.

#1444 V2.12.0
  changelog.d/20240111_165100_yadudoc1729_GCE_container_support_sc_28238.rst
  changelog.d/20240118_144532_kevin_removed_deprected_compute_funcx.rst
  changelog.d/20240122_102159_30907815+rjmello_retain_uep_config_exception.rst
  changelog.d/20240123_115035_kevin_update_parsl.rst
  compute_endpoint/globus_compute_endpoint/version.py
  compute_endpoint/setup.py
  compute_sdk/globus_compute_sdk/version.py
  docs/changelog.rst
Labels: no-news-is-good-news, quick-review

#1447 Gracefully handle invalid result msg for HTEngine
  changelog.d/20240205_123835_30907815+rjmello_HEAD.rst
  compute_endpoint/globus_compute_endpoint/engines/high_throughput/engine.py
  compute_endpoint/tests/unit/test_htex.py
Labels: bug

#1448 Add a note about upgrading from previous Action Provider
  docs/actionprovider.rst
Labels: Documentation, no-news-is-good-news, quick-review

#1452 Remove an unused class
  compute_endpoint/globus_compute_endpoint/strategies/base.py
Labels: no-news-is-good-news, quick-review

#1454 Removing dead code. BaseStrategy.notify is never used.
  compute_endpoint/globus_compute_endpoint/strategies/base.py
Labels: no-news-is-good-news, quick-review

#1456 Implement MEP heartbeats
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
  compute_endpoint/globus_compute_endpoint/endpoint/rabbit_mq/__init__.py
  compute_endpoint/tests/unit/test_endpointmanager_unit.py
Labels: no-news-is-good-news

#1457 Use the library we created
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
Labels: no-news-is-good-news, quick-review

#1458 Simplify log formatting
  compute_endpoint/globus_compute_endpoint/logging_config.py
Labels: no-news-is-good-news

#1459 Bump versions for alpha release v2.13.0a2
  compute_endpoint/globus_compute_endpoint/version.py
  compute_endpoint/setup.py
  compute_sdk/globus_compute_sdk/version.py
Labels: no-news-is-good-news, quick-review

#1460 Remove vestigial items from strategy
  compute_endpoint/globus_compute_endpoint/strategies/base.py
  compute_endpoint/globus_compute_endpoint/strategies/kube_simple.py
  compute_endpoint/globus_compute_endpoint/strategies/simple.py
  compute_endpoint/globus_compute_endpoint/strategies/test.py
Labels: no-news-is-good-news, quick-review

#1462 Add py.typed
  changelog.d/20240216_182658_chris_py_typed.rst
  compute_sdk/globus_compute_sdk/py.typed
  compute_sdk/setup.py
Labels: quick-review

#1464 doc: correct getpwnam
  compute_endpoint/globus_compute_endpoint/MULTIUSER_SETUP.md
Labels: no-news-is-good-news, quick-review

#1465 Reduce unnecessary test delays
  compute_endpoint/globus_compute_endpoint/strategies/base.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_interchange.py
Labels: no-news-is-good-news

#1467 Bump versions and collect changelog for release
  changelog.d/20240205_123835_30907815+rjmello_HEAD.rst
  changelog.d/20240208_180713_30907815+rjmello_pasl_htex_encryption.rst
  changelog.d/20240216_182658_chris_py_typed.rst
  compute_endpoint/globus_compute_endpoint/version.py
  compute_endpoint/setup.py
  compute_sdk/globus_compute_sdk/version.py
  docs/changelog.rst
Labels: quick-review

#1473 Enable configuration of AMQP connection handling
  compute_endpoint/globus_compute_endpoint/endpoint/config/config.py
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
Labels: no-news-is-good-news, quick-review

#1472 Support `max_workers_per_node` attr for GCEngine
  changelog.d/20240227_130057_30907815+rjmello_gcengine_max_workers.rst
  compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
  compute_endpoint/tests/unit/test_engines.py
Labels: bug, quick-review

#1469 Bump versions for alpha release
  compute_endpoint/globus_compute_endpoint/version.py
  compute_endpoint/setup.py
  compute_sdk/globus_compute_sdk/version.py
Labels: no-news-is-good-news, quick-review

#1470 Collect changelog and bump versions for release
  changelog.d/20240221_171528_chris_endpoint_subscription_id.rst
  compute_endpoint/globus_compute_endpoint/version.py
  compute_endpoint/setup.py
  compute_sdk/globus_compute_sdk/version.py
  docs/changelog.rst
Labels: no-news-is-good-news, quick-review
