Repository globus/globus-compute, pull requests merged in 2024-08, with the labels that each got.

#1616 Make python-exec replace the existing process
  compute_endpoint/globus_compute_endpoint/cli.py
  compute_endpoint/tests/unit/test_cli_behavior.py
Labels: no-news-is-good-news

#1617 Bump versions and changelog for release v2.25.0
  changelog.d/20240710_113622_30907815+rjmello_tqs_thread_sc_34463.rst
  changelog.d/20240711_182944_yadudoc1729_shell_functions.rst
  changelog.d/20240711_190719_yadudoc1729_mpi_engine_2.rst
  changelog.d/20240725_104852_yadudoc1729_mpi_functions_2.rst
  changelog.d/20240731_163659_yadudoc1729_update_sdk_to_drop_py3_7.rst
  compute_endpoint/globus_compute_endpoint/version.py
  compute_endpoint/setup.py
  compute_sdk/globus_compute_sdk/version.py
  docs/changelog.rst
Labels: no-news-is-good-news, quick-review

#1620 Update K8s example to use GlobusComputeEngine
  docs/endpoints/configs/kube.yaml
Labels: no-news-is-good-news

#1623 update parsl to latest to avoid cryptography version warning
  compute_endpoint/setup.py
Labels: no-news-is-good-news, quick-review

#1625 Include config file content in EP registration
  compute_endpoint/globus_compute_endpoint/endpoint/config/config.py
  compute_endpoint/globus_compute_endpoint/endpoint/config/utils.py
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
  compute_endpoint/tests/unit/test_cli_behavior.py
  compute_endpoint/tests/unit/test_endpoint_unit.py
  compute_endpoint/tests/unit/test_endpointmanager_unit.py
Labels: no-news-is-good-news

#1628 Remove no-longer-needed dependency
  changelog.d/20240814_122332_kevin_remove_websockets_from_dependency.rst
  compute_sdk/setup.py
Labels: quick-review

#1627 Bump versions and changelog for release v2.26.0
  changelog.d/20240807_114300_30907815+rjmello_HEAD.rst
  changelog.d/20240807_183559_30907815+rjmello_gcengine_with_k8s_provider_sc_33870.rst
  compute_endpoint/globus_compute_endpoint/version.py
  compute_endpoint/setup.py
  compute_sdk/globus_compute_sdk/version.py
  docs/changelog.rst
Labels: no-news-is-good-news

#1629 Fix broken MPI test
  compute_endpoint/tests/conftest.py
Labels: no-news-is-good-news, quick-review

#1633 Submit message to function
  compute_endpoint/tests/integration/test_rabbit_mq/test_task_q.py
Labels: no-news-is-good-news, quick-review

#1634 Test-await the thing under test
  compute_endpoint/tests/integration/test_rabbit_mq/test_task_q.py
Labels: no-news-is-good-news, quick-review

#1632 Add alpha release procedure to RELEASING.md
  RELEASING.md
Labels: no-news-is-good-news

#1635 Reduce test log noise
  compute_endpoint/tests/integration/endpoint/endpoint/test_interchange.py
Labels: no-news-is-good-news, quick-review

#1636 Fix test-passed data
  compute_endpoint/tests/unit/test_engines.py
Labels: no-news-is-good-news

#1637 Bump versions and changelog for release v2.27.0
  changelog.d/20240811_174452_chris_remove_whitelist.rst
  changelog.d/20240814_122332_kevin_remove_websockets_from_dependency.rst
  changelog.d/20240814_145223_30907815+rjmello.rst
  compute_endpoint/globus_compute_endpoint/version.py
  compute_endpoint/setup.py
  compute_sdk/globus_compute_sdk/version.py
  docs/changelog.rst
Labels: no-news-is-good-news

#1640 Update CI job timing
  .github/workflows/ci.yaml
Labels: no-news-is-good-news, quick-review

#1638 Do not prematurely create (default) Engine
  compute_endpoint/globus_compute_endpoint/endpoint/config/config.py
Labels: no-news-is-good-news, quick-review

#1641 Remove long-deprecated args to Client
  changelog.d/20240821_225122_kevin_remove_long_deprecated_client_args.rst
  compute_sdk/globus_compute_sdk/sdk/client.py
Labels: quick-review

#1642 Move tests to their own unit file
  compute_endpoint/tests/unit/test_config_utils.py
  compute_endpoint/tests/unit/test_endpointmanager_unit.py
Labels: no-news-is-good-news, quick-review

#1643 Remove network lookup for rendering UTs
  compute_endpoint/tests/unit/test_config_utils.py
Labels: no-news-is-good-news, quick-review

#1645 Reduce test noise
  compute_endpoint/tests/unit/test_endpointinterchange.py
Labels: no-news-is-good-news, quick-review

#1647 Move conf debug emission to preexec
  compute_endpoint/globus_compute_endpoint/cli.py
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
  compute_endpoint/globus_compute_endpoint/logging_config.py
  compute_endpoint/tests/unit/test_cli_behavior.py
  compute_endpoint/tests/unit/test_endpointmanager_unit.py
Labels: no-news-is-good-news

#1650 Remove test-induced warning
  compute_endpoint/tests/integration/endpoint/executors/test_gcengine_retries.py
Labels: no-news-is-good-news, quick-review

#1649 Do not needlessly instantiate an Engine
  compute_endpoint/tests/unit/test_endpointmanager_unit.py
Labels: no-news-is-good-news, quick-review

#1651 Updating retry tests to use mocked executors
  compute_endpoint/tests/integration/endpoint/executors/test_gcengine_retries.py
Labels: no-news-is-good-news
