Repository globus/globus-compute, pull requests merged in 2024-04, with the labels that each got.

#1512 Remove skipped, now stale tests
  compute_endpoint/tests/integration/endpoint/endpoint/test_interchange.py
Labels: no-news-is-good-news, quick-review

#1513 Refactor (DRY) test file with fixtures
  compute_endpoint/tests/integration/endpoint/endpoint/test_interchange.py
Labels: no-news-is-good-news, quick-review

#1515 update release doc inline with current procedures
  RELEASING.md
Labels: no-news-is-good-news, quick-review

#1514 bump versions for production release of 2.17.0
  changelog.d/20240326_114255_kevin_mu_more_robust_aws_amq_interaction.rst
  changelog.d/20240326_153234_30907815+rjmello_gc_common_pydantic_sc_26075.rst
  changelog.d/20240328_144808_kevin_address_fail_counter_race_condition_reset.rst
  compute_endpoint/globus_compute_endpoint/version.py
  compute_endpoint/setup.py
  compute_sdk/globus_compute_sdk/version.py
  docs/changelog.rst
Labels: no-news-is-good-news, quick-review

#1516 Update README.rst
  README.rst
Labels: no-news-is-good-news

#1517 Add type-checking to a function
  compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
Labels: no-news-is-good-news, quick-review

#1520 Rename links from funcx-faas GitHub org
  .github/_support/github-slack-notify.py
  README.rst
  compute_endpoint/packaging/debian/copyright
  compute_endpoint/setup.py
  compute_sdk/setup.py
  docs/changelog.rst
  docs/sdk.rst
  smoke_tests/tox.ini
Labels: no-news-is-good-news, quick-review

#1522 Update the documentation to reflect the 10MB data limit
  docs/limits.rst
Labels: Documentation, no-news-is-good-news

#1523 Update pinning workers config to use GCEngine
  docs/configs/worker_pinning.yaml
  docs/configuring.rst
Labels: no-news-is-good-news

#1524 Fix breaking change for HighThroughputExecutor
  changelog.d/20240411_134946_chris_hotfix.rst
  compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
Labels: quick-review

#1526 Package shim for SEPs
  compute_endpoint/packaging/Makefile
  compute_endpoint/packaging/debian/rules
  compute_endpoint/packaging/package_shim.sh
Labels: no-news-is-good-news, quick-review

#1521 Create an RPM package of the Endpoint
  compute_endpoint/packaging/Makefile
  compute_endpoint/packaging/create-prereqs-tarball.sh
  compute_endpoint/packaging/debian/changelog.in.in
  compute_endpoint/packaging/debian/rules
  compute_endpoint/packaging/fedora/globus-compute-endpoint.spec.in
Labels: no-news-is-good-news

#1527 Rename package to `globus-compute-agent`
  compute_endpoint/packaging/Makefile
  compute_endpoint/packaging/debian/changelog.in.in
  compute_endpoint/packaging/debian/control
  compute_endpoint/packaging/debian/copyright
  compute_endpoint/packaging/debian/rules
  compute_endpoint/packaging/fedora/globus-compute-agent.spec.in
Labels: no-news-is-good-news

#1529 Remove unused fixture
  compute_sdk/tests/conftest.py
Labels: no-news-is-good-news, quick-review

#1528 Expand pyzmq supported versions to <27.0.0
  changelog.d/20240415_191133_30907815+rjmello_extend_pyzmq_version_range.rst
  compute_endpoint/setup.py
Labels: quick-review

#1530 Remove now-stale code
  compute_endpoint/globus_compute_endpoint/endpoint/config/utils.py
  docs/changelog.rst
  docs/funcx_upgrade.rst
  docs/quickstart.rst
  docs/sdk.rst
Labels: no-news-is-good-news, quick-review

#1536 Fix OpenSUSE rpm builds
  compute_endpoint/packaging/Makefile
  compute_endpoint/packaging/fedora/globus-compute-agent.spec.in
Labels: no-news-is-good-news, quick-review

#1537 Fix test that uses /proc so it works on macOS
  compute_endpoint/tests/unit/test_logging_config.py
Labels: no-news-is-good-news, quick-review

#1534 Create docker compose workflow for EP dev
  endpoint_dev.Dockerfile
  local_dev/.gitignore
  local_dev/README.md
  local_dev/compose.yml
Labels: no-news-is-good-news

#1540 Raise error for incompatible engine and strategy
  changelog.d/20240418_203003_30907815+rjmello_validate_strategy_field_sc_33155.rst
  compute_endpoint/globus_compute_endpoint/endpoint/config/model.py
  compute_endpoint/tests/unit/test_endpoint_config.py
Labels: bug, quick-review

#1533 Update docs to use GlobusComputeEngine
  docs/_static/images/31174D02-Cooley800.jpg
  docs/_static/images/ALCF-Theta_111016-1000px.jpg
  docs/_static/images/stampede2.jpg
  docs/configs/cooley.yaml
  docs/configs/expanse.yaml
  docs/configs/frontera.yaml
  docs/configs/midway.yaml
  docs/configs/polaris.yaml
  docs/configs/stampede2.yaml
  docs/configs/theta.yaml
  docs/configs/theta_singularity.yaml
  docs/configuring.rst
Labels: no-news-is-good-news

#1544 Updating Perlmutter config to use GCE
  docs/configs/perlmutter.yaml
Labels: no-news-is-good-news

#1547 Bump versions and changelog for release v2.19.0
  changelog.d/20240415_191133_30907815+rjmello_extend_pyzmq_version_range.rst
  changelog.d/20240418_203003_30907815+rjmello_validate_strategy_field_sc_33155.rst
  compute_endpoint/globus_compute_endpoint/version.py
  compute_endpoint/setup.py
  compute_sdk/globus_compute_sdk/version.py
  docs/changelog.rst
Labels: no-news-is-good-news

#1548 Snapshot per-task uep submission configuration
  compute_sdk/globus_compute_sdk/sdk/executor.py
  compute_sdk/tests/unit/test_executor.py
Labels: no-news-is-good-news, quick-review

#1546 Add amqp_port setting documentation in the Executor
  docs/executor.rst
Labels: no-news-is-good-news, quick-review

#1545 Updating UChicago AI cluster config to use GCE
  docs/configs/uchicago_ai_cluster.yaml
Labels: no-news-is-good-news

#1539 Add Bebop GCE config
  docs/configs/bebop.yaml
Labels: Documentation, no-news-is-good-news

#1549 Daemonize threads, and still shutdown gracefully
  changelog.d/20240427_105242_kevin_gracefully_shutdown_after_broken_mq_connection.rst
  compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_interchange.py
Labels: quick-review
