Repository globus/globus-compute, pull requests merged in 2024-05, with the labels that each got.

#1551 Enable users to define per-task resource specs
  compute_sdk/globus_compute_sdk/sdk/batch.py
  compute_sdk/globus_compute_sdk/sdk/client.py
  compute_sdk/globus_compute_sdk/sdk/executor.py
  compute_sdk/tests/unit/test_executor.py
Labels: no-news-is-good-news

#1555 chore: [sc-32323] Update example configs to use GlobusComputeEngine
  docs/configs/anvil.yaml
  docs/configs/delta.yaml
  docs/configs/faster.yaml
Labels: no-news-is-good-news

#1554 Implement CI building
  compute_endpoint/packaging/JenkinsFile
  compute_endpoint/packaging/Makefile
  compute_endpoint/packaging/create-prereqs-tarball.sh
  compute_endpoint/packaging/debian/changelog.in.in
  compute_endpoint/packaging/debian/control
  compute_endpoint/packaging/debian/rules
  compute_endpoint/packaging/fedora/globus-compute-agent.spec.in
Labels: no-news-is-good-news

#1556 Updating Bridges2 config to use GCE
  docs/configs/bridges-2.yaml
Labels: no-news-is-good-news

#1557 Working toward publishing builds
  compute_endpoint/packaging/JenkinsFile
  compute_endpoint/packaging/Makefile
Labels: no-news-is-good-news, quick-review

#1558 remove bluewater config
  docs/configs/bluewaters.yaml
  docs/configuring.rst
Labels: no-news-is-good-news, quick-review

#1542 Adds new document section on GCE specific options
  docs/configuring.rst
Labels: no-news-is-good-news

#1559 detach_endpoint isn't a thing on MEP
  compute_endpoint/globus_compute_endpoint/boot_persistence.py
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
  compute_endpoint/tests/unit/test_boot_persistence.py
Labels: no-news-is-good-news, quick-review

#1560 Unhide `configure --multi-user`
  compute_endpoint/globus_compute_endpoint/cli.py
Labels: no-news-is-good-news, quick-review

#1562 Test already committed work
  compute_endpoint/tests/unit/test_endpointmanager_unit.py
Labels: no-news-is-good-news, quick-review

#1563 Update quickstart to specify --include-deps
  docs/quickstart.rst
Labels: Documentation, no-news-is-good-news

#1564 include deps option added to Documentation - part deux
  docs/endpoints.rst
Labels: no-news-is-good-news, quick-review

#1561 Make Executor shutdown idempotent
  changelog.d/20240508_000749_kevin_idempotent_executor_shutdown.rst
  compute_sdk/globus_compute_sdk/sdk/executor.py
  compute_sdk/tests/unit/test_executor.py
Labels: no-news-is-good-news, quick-review

#1565 Bump versions for QA release v2.20.0a1
  compute_endpoint/globus_compute_endpoint/version.py
  compute_endpoint/setup.py
  compute_sdk/globus_compute_sdk/version.py
Labels: no-news-is-good-news, quick-review

#1567 Remove SafetyCLI from GH actions
  .github/workflows/ci.yaml
  .github/workflows/daily.yaml
  compute_endpoint/tox.ini
  compute_sdk/tox.ini
Labels: no-news-is-good-news, quick-review

#1568 add --include-deps to pipx install examples
  docs/endpoints/single_user.rst
  docs/index.rst
  docs/quickstart.rst
Labels: Documentation, no-news-is-good-news, quick-review

#1569 Respond to PR comments
  docs/endpoints/multi_user.rst
  docs/endpoints/single_user.rst
Labels: no-news-is-good-news

#1573 Stop immediately on unrecoverable error
  changelog.d/20240523_154926_kevin_stop_mep_unrecoverable_auth_error.rst
  compute_endpoint/globus_compute_endpoint/endpoint/rabbit_mq/command_queue_subscriber.py
  compute_endpoint/globus_compute_endpoint/endpoint/rabbit_mq/result_publisher.py
  compute_endpoint/tests/unit/test_command_queue_subscriber.py
  compute_endpoint/tests/unit/test_result_publisher.py
Labels: quick-review

#1574 Remove unused assignment
  compute_endpoint/globus_compute_endpoint/endpoint/rabbit_mq/result_publisher.py
Labels: no-news-is-good-news, quick-review

#1576 Build SDK as well as endpoint wheel for packaging
  compute_endpoint/packaging/Makefile
  compute_endpoint/packaging/create-prereqs-tarball.sh
Labels: no-news-is-good-news

#1577 Updating Midway config to use GCE
  docs/endpoints/configs/midway.yaml
Labels: no-news-is-good-news, quick-review

#1578 Bump versions for release of v2.21.0
  changelog.d/20240427_105242_kevin_gracefully_shutdown_after_broken_mq_connection.rst
  changelog.d/20240429_144311_chris_package_systemd_unit.rst
  changelog.d/20240508_000749_kevin_idempotent_executor_shutdown.rst
  changelog.d/20240516_124159_30907815+rjmello_user_config_j2_ext_sc_33651.rst
  changelog.d/20240517_150132_chris_pass_parent_config_to_template.rst
  changelog.d/20240523_121518_30907815+rjmello_self_diag_mep_sc_33745.rst
  changelog.d/20240523_154926_kevin_stop_mep_unrecoverable_auth_error.rst
  compute_endpoint/globus_compute_endpoint/version.py
  compute_endpoint/setup.py
  compute_sdk/globus_compute_sdk/version.py
  docs/changelog.rst
Labels: no-news-is-good-news, quick-review

#1579 Delineate changes from v2.20.0 and v2.21.0
  docs/changelog.rst
Labels: no-news-is-good-news, quick-review
