Repository globus/globus-compute, pull requests merged in 2024-12, with the labels that each got.

#1733 Document auth caching implementation
  docs/endpoints/multi_user.rst
Labels: no-news-is-good-news, quick-review

#1736 Reduce variable scope
  compute_endpoint/globus_compute_endpoint/cli.py
Labels: no-news-is-good-news, quick-review

#1738 bump versions and collect changelog for V2.32.0 release
  changelog.d/20241114_172127_chris_remove_tty_checks.rst
  changelog.d/20241120_120234_30907815+rjmello_fix_client_logout.rst
  changelog.d/20241121_110717_kevin_relax_jsonschema_constraint.rst
  changelog.d/20241126_104747_LeiGlobus_bump_parsl_11_25.rst
  compute_endpoint/globus_compute_endpoint/version.py
  compute_endpoint/setup.py
  compute_sdk/globus_compute_sdk/version.py
  docs/changelog.rst
Labels: no-news-is-good-news, quick-review

#1740 Bump versions and changelog for hotfix v2.32.1
  compute_endpoint/globus_compute_endpoint/endpoint/config/__init__.py
  compute_endpoint/globus_compute_endpoint/endpoint/config/model.py
  compute_endpoint/globus_compute_endpoint/endpoint/config/utils.py
  compute_endpoint/globus_compute_endpoint/version.py
  compute_endpoint/setup.py
  compute_endpoint/tests/unit/test_endpoint_config.py
  compute_sdk/globus_compute_sdk/version.py
  docs/changelog.rst
Labels: no-news-is-good-news

#1741 Allow UEPs to restrict functions
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
  compute_endpoint/tests/unit/test_endpointmanager_unit.py
Labels: no-news-is-good-news, quick-review

#1735 document package pushing procedures
  RELEASING.md
Labels: no-news-is-good-news

#1742 Bumped dill dependency to v0.3.9 for Python 3.11+
  changelog.d/20241205_121009_30907815+rjmello_bum_dill_v0_3_9.rst
  compute_sdk/setup.py
Labels: quick-review

#1743 Touch up Security Posture section
  docs/endpoints/multi_user.rst
Labels: no-news-is-good-news

#1729 Replace ipv4 v6 sc 37307
  compute_endpoint/globus_compute_endpoint/endpoint/taskqueue.py
  compute_endpoint/globus_compute_endpoint/engines/high_throughput/engine.py
  compute_endpoint/globus_compute_endpoint/engines/high_throughput/interchange.py
  compute_endpoint/globus_compute_endpoint/engines/high_throughput/manager.py
  compute_endpoint/globus_compute_endpoint/engines/high_throughput/worker.py
  compute_endpoint/globus_compute_endpoint/engines/high_throughput/zmq_pipes.py
  compute_endpoint/tests/conftest.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint_manager.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_gcengine_strategy.py
  compute_endpoint/tests/integration/endpoint/executors/test_gcengine_retries.py
  compute_endpoint/tests/unit/test_bad_endpoint_config.py
  compute_endpoint/tests/unit/test_cli_behavior.py
  compute_endpoint/tests/unit/test_endpoint_config.py
  compute_endpoint/tests/unit/test_endpoint_unit.py
  compute_endpoint/tests/unit/test_engines.py
  compute_endpoint/tests/unit/test_gce_container.py
  compute_endpoint/tests/unit/test_reporting_period.py
  compute_endpoint/tests/unit/test_worker.py
  compute_endpoint/tests/unit/test_working_dir.py
  compute_sdk/tests/unit/test_login_manager.py
  docs/autobuild.sh
Labels: no-news-is-good-news

#1744 Add port 443 of amqp host to diagnostics
  compute_sdk/globus_compute_sdk/sdk/diagnostic.py
Labels: no-news-is-good-news, quick-review

#1746 Apply linear backoff strategy to Client smoke tests
  smoke_tests/tests/conftest.py
  smoke_tests/tests/test_running_functions.py
Labels: no-news-is-good-news

#1747 Remove no-longer necessary test-skips
  smoke_tests/tests/conftest.py
  smoke_tests/tests/test_running_functions.py
  smoke_tests/tests/test_s3_indirect.py
Labels: no-news-is-good-news, quick-review

#1748 Bump versions and changelog for release v2.33.0
  changelog.d/20241115_095433_kevin_implement_pam_for_meps.rst
  changelog.d/20241205_121009_30907815+rjmello_bum_dill_v0_3_9.rst
  compute_endpoint/globus_compute_endpoint/version.py
  compute_endpoint/setup.py
  compute_sdk/globus_compute_sdk/version.py
  docs/changelog.rst
Labels: no-news-is-good-news

#1749 Add request_id to ComputeFuture._metadata
  compute_sdk/globus_compute_sdk/sdk/executor.py
  compute_sdk/tests/unit/test_executor.py
Labels: no-news-is-good-news, quick-review

#1750 Correct formatting, add warning
  compute_endpoint/globus_compute_endpoint/endpoint/config/config.py
Labels: no-news-is-good-news, quick-review
