Repository globus/globus-compute, pull requests merged in 2024-03, with the labels that each got.

#1477 Bump globus-identity-mapper to 0.3.0
  changelog.d/20240301_101449_kevin_update_gim_to_030.rst
  compute_endpoint/setup.py
Labels: quick-review

#1478 Two dependency updates
  changelog.d/20240301_105729_kevin_update_two_deps.rst
  compute_endpoint/setup.py
  compute_sdk/setup.py
Labels: quick-review

#1480 Do not escape containerized launch command
  changelog.d/20240302_235505_30907815+rjmello_container_launch_cmd.rst
  compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
  compute_endpoint/tests/integration/endpoint/executors/high_throughput/test_gce_container.py
Labels: bug

#1481 Ensure parsl logs propagate
  changelog.d/20240305_135742_30907815+rjmello.rst
  compute_endpoint/globus_compute_endpoint/logging_config.py
  compute_endpoint/tests/unit/test_logging_config.py
Labels: bug, quick-review

#1479 Include user config template in MEP registration
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
  compute_endpoint/tests/unit/test_endpointmanager_unit.py
Labels: no-news-is-good-news

#1484 Remove `max_workers` rename in GCEngine
  changelog.d/20240227_130057_30907815+rjmello_gcengine_max_workers.rst
  compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
Labels: no-news-is-good-news

#1486 Include `display_name` in MEP registration payload
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
  compute_endpoint/tests/unit/test_endpointmanager_unit.py
Labels: bug, no-news-is-good-news, quick-review

#1487 Remove a no-longer-necessary branch (#617)
  smoke_tests/tests/test_running_functions.py
Labels: no-news-is-good-news, quick-review

#1482 Add login command
  changelog.d/20240306_142334_chris_login_command.rst
  compute_endpoint/globus_compute_endpoint/cli.py
  compute_endpoint/tests/unit/test_cli_behavior.py
Labels: quick-review

#1485 Bump version for alpha release
  compute_endpoint/globus_compute_endpoint/version.py
  compute_endpoint/setup.py
  compute_sdk/globus_compute_sdk/version.py
  smoke_tests/tests/test_version.py
Labels: no-news-is-good-news, quick-review

#1489 Bump versions and changelog for release
  changelog.d/20240301_101449_kevin_update_gim_to_030.rst
  changelog.d/20240301_105729_kevin_update_two_deps.rst
  changelog.d/20240302_235505_30907815+rjmello_container_launch_cmd.rst
  changelog.d/20240305_135742_30907815+rjmello.rst
  changelog.d/20240308_113821_yadudoc1729_bump_parsl_pinned_version_to_2023_3_4.rst
  compute_endpoint/globus_compute_endpoint/version.py
  compute_endpoint/setup.py
  compute_sdk/globus_compute_sdk/version.py
  docs/changelog.rst
Labels: quick-review

#1493 Add support for `public` config field
  compute_endpoint/globus_compute_endpoint/endpoint/config/config.py
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint.py
  compute_endpoint/tests/unit/test_endpoint_config.py
  compute_endpoint/tests/unit/test_endpointmanager_unit.py
  compute_sdk/globus_compute_sdk/sdk/client.py
  compute_sdk/globus_compute_sdk/sdk/web_client.py
Labels: no-news-is-good-news

#1495 Bump parsl pinned version to 2023.3.18
  changelog.d/20240321_121200_kevin_update_parsl.rst
  compute_endpoint/setup.py
Labels: quick-review

#1497 update release notes and add git auto push tag
  RELEASING.md
  release.sh
Labels: no-news-is-good-news, quick-review

#1498 Add Parsl workflow example to docs
  docs/tutorial.rst
Labels: no-news-is-good-news

#1501 Mild test refactor
  compute_endpoint/tests/unit/test_command_queue_subscriber.py
  compute_endpoint/tests/unit/test_result_publisher.py
Labels: no-news-is-good-news, quick-review

#1500 Replace `funcx_service_address` with `local_compute_services`
  compute_endpoint/globus_compute_endpoint/endpoint/config/config.py
  compute_endpoint/globus_compute_endpoint/endpoint/config/model.py
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
  compute_endpoint/globus_compute_endpoint/engines/base.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint_manager.py
  compute_endpoint/tests/unit/test_endpoint_unit.py
  compute_endpoint/tests/unit/test_endpointmanager_unit.py
  compute_sdk/globus_compute_sdk/sdk/client.py
  compute_sdk/globus_compute_sdk/sdk/login_manager/decorators.py
  compute_sdk/tests/conftest.py
  compute_sdk/tests/integration/test_executor_int.py
  compute_sdk/tests/unit/test_client.py
  compute_sdk/tests/unit/test_login_manager.py
  examples/AsyncFuncXExample.ipynb
  smoke_tests/tests/conftest.py
Labels: no-news-is-good-news

#1506 Fully support Pydantic V2
  changelog.d/20240326_153234_30907815+rjmello_gc_common_pydantic_sc_26075.rst
  compute_endpoint/setup.py
  compute_endpoint/tox.ini
  compute_sdk/setup.py
Labels: no-news-is-good-news

#1507 Reset retry counter after 2 HBs
  changelog.d/20240328_144808_kevin_address_fail_counter_race_condition_reset.rst
  compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
  compute_endpoint/tests/unit/test_endpointinterchange.py
Labels: quick-review
