Repository globus/globus-compute, pull requests merged in 2025-09, with the labels that each got.

#1922 Refactor endpoint docs for v4 architecture changes
  docs/endpoints/config_reference.rst
  docs/endpoints/configs/anvil.yaml
  docs/endpoints/configs/bebop.yaml
  docs/endpoints/configs/delta.yaml
  docs/endpoints/configs/expanse.yaml
  docs/endpoints/configs/expanse_mpi.yaml
  docs/endpoints/configs/faster.yaml
  docs/endpoints/configs/frontera.yaml
  docs/endpoints/configs/ospool.yaml
  docs/endpoints/configs/perlmutter.yaml
  docs/endpoints/configs/polaris.yaml
  docs/endpoints/configs/stampede3.yaml
  docs/endpoints/configs/uchicago_ai_cluster.yaml
  docs/endpoints/endpoint_examples.rst
  docs/endpoints/endpoints.rst
  docs/endpoints/index.rst
  docs/endpoints/installation.rst
  docs/endpoints/multi_user.rst
  docs/endpoints/security_posture.rst
  docs/endpoints/templates.rst
  docs/tutorials/dynamic_containers.rst
Labels: Documentation, no-news-is-good-news

#1929 Remove webhook usage for GitHub
  .github/_support/github-slack-notify.py
  .github/workflows/hourly.yaml
Labels: no-news-is-good-news, quick-review

#1931 Handle null user values when rendering template
  changelog.d/20250909_155630_30907815+rjmello_handle_null_user_values_sc_44820.rst
  compute_endpoint/globus_compute_endpoint/endpoint/config/utils.py
  compute_endpoint/tests/unit/test_config_utils.py
Labels: bug

#1941 Bump versions and collect change-log for release 3.15.0
  changelog.d/20250916_144323_30907815+rjmello_bump_parsl_2025_09_15.rst
  changelog.d/20250916_151835_30907815+rjmello_python_mismatch_sc_31360.rst
  changelog.d/20250919_102327_kevin_two_instances_of_same_ep_fix.rst
  compute_endpoint/globus_compute_endpoint/version.py
  compute_endpoint/setup.py
  compute_sdk/globus_compute_sdk/version.py
  docs/changelog.rst
Labels: no-news-is-good-news
