Repository globus/globus-compute, pull requests merged in 2025-05, with the labels that each got.

#1866 Mention user runtime in UEP identifer hash docs
  docs/endpoints/multi_user.rst
Labels: no-news-is-good-news

#1870 Add a function for handling GAREs
  compute_sdk/globus_compute_sdk/sdk/utils/gare.py
  compute_sdk/tests/unit/test_util.py
Labels: no-news-is-good-news

#1873 Bump Globus SDK for cleaner GARE handler
  changelog.d/20250506_185402_chris_update_gare_handler.rst
  compute_sdk/globus_compute_sdk/sdk/utils/gare.py
  compute_sdk/setup.py
Labels: quick-review

#1871 Handle GAREs in create auth policy code
  changelog.d/20250505_113845_chris_gare_handle_create_auth_policy.rst
  compute_endpoint/globus_compute_endpoint/cli.py
  compute_endpoint/tests/unit/test_cli_behavior.py
Labels: quick-review

#1869 v3.7.0 Release Branch
  changelog.d/20250423_130657_nicholas.s.tyler.4_add_podman_hpc.rst
  changelog.d/20250428_144312_30907815+rjmello_escape_user_runtime.rst
  compute_endpoint/globus_compute_endpoint/version.py
  compute_endpoint/setup.py
  compute_sdk/globus_compute_sdk/version.py
  docs/changelog.rst
Labels: no-news-is-good-news

#1876 Add a stricter upper bound for click version
  compute_endpoint/setup.py
Labels: no-news-is-good-news, quick-review

#1877 Convert persistent_volumes to a list of tuples
  changelog.d/20250513_102548_30907815+rjmello_k8s_pers_vol_type.rst
  compute_endpoint/globus_compute_endpoint/endpoint/config/model.py
  compute_endpoint/tests/unit/test_endpoint_config.py
Labels: quick-review

#1878 Decouple task collection from group reload
  compute_sdk/globus_compute_sdk/sdk/executor.py
  compute_sdk/tests/unit/test_executor.py
Labels: no-news-is-good-news

#1882 Lock-guard all client requests
  compute_sdk/globus_compute_sdk/sdk/client.py
  compute_sdk/tests/unit/test_client.py
Labels: no-news-is-good-news, quick-review

#1881 Remove legacy get_containers method
  changelog.d/20250516_095252_30907815+rjmello_remove_get_containers.rst
  compute_sdk/globus_compute_sdk/sdk/client.py
  compute_sdk/tests/unit/test_client.py
Labels: quick-review

#1884 Bump versions and changelog for release v3.8.0
  changelog.d/20250505_113845_chris_gare_handle_create_auth_policy.rst
  changelog.d/20250506_185402_chris_update_gare_handler.rst
  changelog.d/20250513_102548_30907815+rjmello_k8s_pers_vol_type.rst
  changelog.d/20250514_105934_30907815+rjmello_ep_admins.rst
  changelog.d/20250515_080955_kevin_executor_handles_ha_tasks.rst
  changelog.d/20250516_095252_30907815+rjmello_remove_get_containers.rst
  changelog.d/20250519_100900_30907815+rjmello_deprecate_legacy_containers_sc_32334.rst
  compute_endpoint/globus_compute_endpoint/version.py
  compute_endpoint/setup.py
  compute_sdk/globus_compute_sdk/version.py
  docs/changelog.rst
Labels: no-news-is-good-news

#1885 Update release readme for package building to fix typo and update text
  RELEASING.md
Labels: no-news-is-good-news, quick-review

#1886 Fix missing uep config log message
  compute_endpoint/globus_compute_endpoint/endpoint/config/utils.py
  compute_endpoint/tests/unit/test_config_utils.py
Labels: no-news-is-good-news, quick-review
