Repository globus/globus-compute, pull requests merged in 2025-01, with the labels that each got.

#1751 Replace TODO with link
  docs/sdk.rst
Labels: no-news-is-good-news, quick-review

#1752 Address flaky test; remove use of time
  compute_endpoint/globus_compute_endpoint/engines/base.py
  compute_endpoint/tests/unit/test_reporting_period.py
Labels: no-news-is-good-news, quick-review

#1754 Bump versions for V2.34.0 release
  compute_endpoint/globus_compute_endpoint/version.py
  compute_endpoint/setup.py
  compute_sdk/globus_compute_sdk/version.py
Labels: no-news-is-good-news

#1756 fix possible issue regarding bytes/str decoding
  compute_endpoint/globus_compute_endpoint/engines/high_throughput/messages.py
Labels: no-news-is-good-news, quick-review

#1753 Adding a config example entry for Open Science Pool
  docs/endpoints/configs/ospool.yaml
  docs/endpoints/endpoint_examples.rst
Labels: no-news-is-good-news

#1758 Shutdown engines in test
  compute_endpoint/tests/unit/test_gce_container.py
Labels: no-news-is-good-news, quick-review

#1759 Update Parsl to 2025.1.6
  changelog.d/20250109_115759_kevin_update_parsl.rst
  compute_endpoint/globus_compute_endpoint/endpoint/config/model.py
  compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
  compute_endpoint/setup.py
Labels: quick-review

#1761 Close internal SelectConnection resources
  compute_endpoint/globus_compute_endpoint/endpoint/rabbit_mq/result_publisher.py
  compute_endpoint/globus_compute_endpoint/endpoint/rabbit_mq/task_queue_subscriber.py
  compute_endpoint/tests/integration/test_rabbit_mq/result_queue_subscriber.py
Labels: no-news-is-good-news, quick-review

#1745 Modify release script to distinguish git tag errors
  release.sh
Labels: no-news-is-good-news, quick-review

#1764 Convert test class to threading
  compute_endpoint/globus_compute_endpoint/endpoint/rabbit_mq/result_publisher.py
  compute_endpoint/tests/integration/conftest.py
  compute_endpoint/tests/integration/test_rabbit_mq/result_queue_subscriber.py
  compute_endpoint/tests/integration/test_rabbit_mq/test_rabbit_e2e.py
  compute_endpoint/tests/integration/test_rabbit_mq/test_result_q.py
Labels: no-news-is-good-news

#1763 Check before test ioloop close
  compute_endpoint/globus_compute_endpoint/endpoint/rabbit_mq/task_queue_subscriber.py
  compute_endpoint/tests/integration/conftest.py
  compute_endpoint/tests/integration/test_rabbit_mq/result_queue_subscriber.py
  compute_endpoint/tests/integration/test_rabbit_mq/task_queue_publisher.py
  compute_endpoint/tests/integration/test_rabbit_mq/test_rabbit_e2e.py
  compute_endpoint/tests/integration/test_rabbit_mq/test_task_q.py
Labels: no-news-is-good-news

#1765 Remove obsolete test for MEP config
  compute_endpoint/tests/unit/test_cli_behavior.py
Labels: no-news-is-good-news, quick-review

#1720 add high-assurance placeholder option to endpoint configuration
  compute_endpoint/globus_compute_endpoint/cli.py
  compute_endpoint/globus_compute_endpoint/endpoint/config/config.py
  compute_endpoint/globus_compute_endpoint/endpoint/config/model.py
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint_manager.py
  compute_endpoint/tests/unit/conftest.py
  compute_endpoint/tests/unit/test_cli_behavior.py
  compute_endpoint/tests/unit/test_endpoint_config.py
  compute_endpoint/tests/unit/test_endpointmanager_unit.py
  compute_sdk/globus_compute_sdk/sdk/client.py
  compute_sdk/globus_compute_sdk/sdk/web_client.py
Labels: no-news-is-good-news

#1767 Remove unnecessary c&p fixture
  compute_endpoint/globus_compute_endpoint/endpoint/rabbit_mq/result_publisher.py
  compute_endpoint/tests/integration/test_rabbit_mq/test_result_q.py
Labels: no-news-is-good-news, quick-review

#1766 Close resources with test subprocesses
  compute_endpoint/tests/integration/endpoint/endpoint/test_interchange_with_rabbit.py
Labels: no-news-is-good-news, quick-review

#1769 Document Client.get_batch_status better
  compute_sdk/globus_compute_sdk/sdk/client.py
Labels: no-news-is-good-news, quick-review

#1772 Clean up serialization tests a little
  compute_sdk/tests/unit/test_serialization.py
Labels: no-news-is-good-news, quick-review

#1774 Fix `allowed_serializers` missing in `GlobusComputeEngine` docstring
  compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
Labels: no-news-is-good-news, quick-review

#1775 Remove spurious warning
  compute_endpoint/globus_compute_endpoint/endpoint/rabbit_mq/task_queue_subscriber.py
Labels: no-news-is-good-news, quick-review

#1777 Remove unused variable
  compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
Labels: no-news-is-good-news, quick-review

#1778 Find all matched identities, not just first
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
  compute_endpoint/globus_compute_endpoint/endpoint/identity_mapper.py
  compute_endpoint/tests/unit/test_endpointmanager_unit.py
  compute_endpoint/tests/unit/test_identity_mapper.py
Labels: no-news-is-good-news

#1780 Update Polaris config to use alternate interface for engine communication
  docs/endpoints/configs/polaris.yaml
Labels: no-news-is-good-news, quick-review

#1779 Refactor heartbeat logic
  compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
  compute_endpoint/globus_compute_endpoint/engines/base.py
  compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
  compute_endpoint/globus_compute_endpoint/engines/process_pool.py
  compute_endpoint/globus_compute_endpoint/engines/thread_pool.py
  compute_endpoint/tests/conftest.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_interchange.py
  compute_endpoint/tests/unit/test_endpointinterchange.py
  compute_endpoint/tests/unit/test_gce_container.py
  compute_endpoint/tests/unit/test_reporting_period.py
  compute_endpoint/tests/unit/test_reporting_thread.py
  compute_endpoint/tests/unit/test_status_reporting.py
Labels: no-news-is-good-news

#1762 Process EP heartbeats separately from results
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
  compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
  compute_endpoint/tests/integration/conftest.py
  compute_endpoint/tests/integration/endpoint/conftest.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_interchange.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_interchange_with_rabbit.py
  compute_endpoint/tests/integration/test_rabbit_mq/test_heartbeat_q.py
  compute_endpoint/tests/unit/test_endpoint_unit.py
  compute_endpoint/tests/unit/test_endpointinterchange.py
  compute_endpoint/tests/unit/test_endpointmanager_unit.py
  compute_endpoint/tests/unit/test_utils.py
Labels: no-news-is-good-news

#1782 Bump versions for 3.0.0 release
  changelog.d/20250109_115759_kevin_update_parsl.rst
  changelog.d/20250109_164900_kevin_remove_deprecated_htex.rst
  changelog.d/20250113_150119_chris_restrict_serializers.rst
  compute_endpoint/globus_compute_endpoint/version.py
  compute_endpoint/setup.py
  compute_sdk/globus_compute_sdk/version.py
  docs/changelog.rst
Labels: no-news-is-good-news, quick-review

#1785 Hotfix release v3.0.1
  compute_endpoint/globus_compute_endpoint/endpoint/config/model.py
  compute_endpoint/globus_compute_endpoint/executors/__init__.py
  compute_endpoint/globus_compute_endpoint/providers/__init__.py
  compute_endpoint/globus_compute_endpoint/providers/kubernetes/__init__.py
  compute_endpoint/globus_compute_endpoint/providers/kubernetes/kube.py
  compute_endpoint/globus_compute_endpoint/providers/kubernetes/template.py
  compute_endpoint/globus_compute_endpoint/strategies/__init__.py
  compute_endpoint/globus_compute_endpoint/strategies/base.py
  compute_endpoint/globus_compute_endpoint/strategies/kube_simple.py
  compute_endpoint/globus_compute_endpoint/strategies/simple.py
  compute_endpoint/globus_compute_endpoint/strategies/test.py
  compute_endpoint/globus_compute_endpoint/version.py
  compute_endpoint/setup.py
  compute_endpoint/tests/unit/test_endpoint_config.py
  compute_sdk/globus_compute_sdk/version.py
  docs/changelog.rst
Labels: no-news-is-good-news

#1783 Add static information to EP Info in heartbeat
  compute_endpoint/globus_compute_endpoint/cli.py
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
  compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
  compute_endpoint/globus_compute_endpoint/endpoint/utils/__init__.py
  compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
  compute_endpoint/globus_compute_endpoint/engines/process_pool.py
  compute_endpoint/globus_compute_endpoint/engines/thread_pool.py
  compute_endpoint/tests/conftest.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint_manager.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_interchange.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_interchange_with_rabbit.py
  compute_endpoint/tests/unit/engine/test_globuscompute.py
  compute_endpoint/tests/unit/test_endpoint_unit.py
  compute_endpoint/tests/unit/test_endpointinterchange.py
Labels: no-news-is-good-news
