Repository globus/globus-compute, pull requests merged in 2025-07, with the labels that each got.

#1903 Update serialization mismatch warning url
  compute_sdk/globus_compute_sdk/sdk/utils/__init__.py
Labels: no-news-is-good-news, quick-review

#1901 3.10.0 Release Branch
  changelog.d/20250701_185230_30907815+rjmello_consolidate_sdk_docs_sc_42327.rst
  changelog.d/20250702_101404_30907815+rjmello_stop_endpoint_v3.rst
  compute_endpoint/globus_compute_endpoint/version.py
  compute_endpoint/setup.py
  compute_sdk/globus_compute_sdk/version.py
  docs/changelog.rst
Labels: no-news-is-good-news

#1909 Add alert for container EP package requirement
  docs/endpoints/endpoints.rst
Labels: Documentation, no-news-is-good-news, quick-review

#1915 Separate ShellResult command for copy/paste
  compute_sdk/globus_compute_sdk/sdk/shell_function.py
  compute_sdk/tests/unit/test_shell_functions.py
Labels: no-news-is-good-news, quick-review
