Repository globus/globus-compute, pull requests merged in 2025-04, with the labels that each got.

#1838 Bump versions and collect changelog for 3.5.0 release
  changelog.d/20250325_154559_chris_strategylike.rst
  changelog.d/20250325_160052_chris_pure_source_combined.rst
  compute_endpoint/globus_compute_endpoint/version.py
  compute_endpoint/setup.py
  compute_sdk/globus_compute_sdk/version.py
  docs/changelog.rst
Labels: no-news-is-good-news, quick-review

#1839 Update Parsl pin
  changelog.d/20250402_134420_kevin_update_parsl_pin.rst
  compute_endpoint/setup.py
Labels: quick-review

#1840 Be more precise with test event collection
  compute_endpoint/tests/integration/endpoint/endpoint/test_interchange.py
Labels: no-news-is-good-news

#1841 Make MEP and UEP ha aligned
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
  compute_endpoint/tests/unit/test_endpointmanager_unit.py
Labels: no-news-is-good-news, quick-review

#1843 unhide HA option when configuring
  compute_endpoint/globus_compute_endpoint/cli.py
Labels: no-news-is-good-news, quick-review

#1845 Reduce test wait time
  compute_endpoint/tests/unit/test_engines.py
Labels: no-news-is-good-news, quick-review

#1846 Pass future to engine instead
  compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
  compute_endpoint/globus_compute_endpoint/engines/__init__.py
  compute_endpoint/globus_compute_endpoint/engines/base.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_gcengine_shell_functions.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_interchange.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_interchange_with_rabbit.py
  compute_endpoint/tests/integration/endpoint/executors/mock_executors.py
  compute_endpoint/tests/integration/endpoint/executors/test_engines.py
  compute_endpoint/tests/integration/endpoint/executors/test_gcengine_retries.py
  compute_endpoint/tests/integration/endpoint/executors/test_mpiengine.py
  compute_endpoint/tests/unit/test_engines.py
  compute_endpoint/tests/unit/test_working_dir.py
Labels: no-news-is-good-news

#1847 Disable Globus SDK retries in tests
  compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint.py
Labels: no-news-is-good-news, quick-review

#1848 Fix errant test
  compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint.py
Labels: no-news-is-good-news, quick-review

#1850 context manager not needed for RequestsMock
  compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint.py
Labels: no-news-is-good-news, quick-review

#1842 Add MFA flag to policy creation when configuring Endpoint
  compute_endpoint/globus_compute_endpoint/cli.py
  compute_endpoint/tests/unit/test_cli_behavior.py
Labels: no-news-is-good-news

#1849 Teach GCFuture executor_task_id
  compute_endpoint/globus_compute_endpoint/engines/base.py
  compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
  compute_endpoint/globus_compute_endpoint/engines/globus_mpi.py
  compute_endpoint/globus_compute_endpoint/engines/process_pool.py
  compute_endpoint/globus_compute_endpoint/engines/thread_pool.py
  compute_endpoint/tests/integration/endpoint/executors/test_gcengine_retries.py
  compute_endpoint/tests/unit/engine/conftest.py
  compute_endpoint/tests/unit/engine/test_globuscompute.py
  compute_endpoint/tests/unit/engine/test_globusmpi.py
  compute_endpoint/tests/unit/engine/test_processpool.py
  compute_endpoint/tests/unit/engine/test_threadpool.py
  compute_endpoint/tests/unit/test_engines.py
  compute_endpoint/tests/unit/test_gcfuture.py
Labels: no-news-is-good-news

#1853 remove reference to Globus RPM-GPG-KEY from DEB and RPM instructions
  docs/endpoints/installation.rst
Labels: no-news-is-good-news, quick-review

#1854 Remove unnecessary engine instantiation in tests
  compute_endpoint/tests/unit/test_cli_behavior.py
Labels: no-news-is-good-news, quick-review

#1852 Add Parsl monitoring queue
  compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
  compute_endpoint/globus_compute_endpoint/engines/base.py
  compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_gcengine_shell_functions.py
  compute_endpoint/tests/integration/endpoint/executors/test_engines.py
  compute_endpoint/tests/integration/endpoint/executors/test_gcengine_retries.py
  compute_endpoint/tests/integration/endpoint/executors/test_mpiengine.py
  compute_endpoint/tests/unit/engine/test_base.py
  compute_endpoint/tests/unit/engine/test_globuscompute.py
  compute_endpoint/tests/unit/engine/test_globusmpi.py
  compute_endpoint/tests/unit/engine/test_processpool.py
  compute_endpoint/tests/unit/engine/test_threadpool.py
  compute_endpoint/tests/unit/test_engines.py
  compute_endpoint/tests/unit/test_gcfuture.py
  compute_endpoint/tests/unit/test_working_dir.py
Labels: no-news-is-good-news

#1857 Implement UEP audit method
  compute_endpoint/globus_compute_endpoint/cli.py
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
  compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_interchange.py
  compute_endpoint/tests/integration/endpoint/executors/mock_executors.py
  compute_endpoint/tests/unit/test_cli_behavior.py
  compute_endpoint/tests/unit/test_endpoint_unit.py
  compute_endpoint/tests/unit/test_endpointinterchange.py
Labels: no-news-is-good-news

#1859 Ensure failed audit setup shuts down MEP
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
  compute_endpoint/tests/unit/test_mep_audit_log.py
Labels: quick-review

#1860 change HA policy creation to be based on configure HA flag, not timeout
  compute_endpoint/globus_compute_endpoint/cli.py
  compute_endpoint/tests/unit/test_cli_behavior.py
Labels: no-news-is-good-news, quick-review

#1862 remove language that associates timeouts with high-assurance
  compute_endpoint/globus_compute_endpoint/cli.py
Labels: Documentation, no-news-is-good-news, quick-review

#1861 Bump versions for prod release 3.6.0
  changelog.d/20250328_153123_chris_result_serde.rst
  changelog.d/20250402_134420_kevin_update_parsl_pin.rst
  changelog.d/20250404_172727_30907815+rjmello_ha_endpoint_id.rst
  compute_endpoint/globus_compute_endpoint/cli.py
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
  compute_endpoint/globus_compute_endpoint/version.py
  compute_endpoint/setup.py
  compute_endpoint/tests/unit/test_cli_behavior.py
  compute_endpoint/tests/unit/test_mep_audit_log.py
  compute_sdk/globus_compute_sdk/version.py
  compute_sdk/setup.py
  docs/changelog.rst
Labels: no-news-is-good-news, quick-review

#1865 Invert mistaken boolean conditional
  compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_interchange.py
Labels: no-news-is-good-news, quick-review

#1868 Remove unused event
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
Labels: no-news-is-good-news, quick-review
