Repository globus/globus-compute, pull requests merged in 2025-03, with the labels that each got.

#1824 Add util.get_py_version_str() to SDK
  compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
  compute_endpoint/tests/unit/engine/test_globuscompute.py
  compute_sdk/globus_compute_sdk/sdk/utils/__init__.py
  compute_sdk/globus_compute_sdk/sdk/web_client.py
  compute_sdk/tests/unit/test_client.py
Labels: no-news-is-good-news, quick-review

#1825 Update Batch user guide section
  docs/reference/client.rst
  docs/sdk.rst
Labels: no-news-is-good-news

#1826 Bump versions and collect changelog for re-release
  compute_endpoint/globus_compute_endpoint/version.py
  compute_endpoint/setup.py
  compute_sdk/globus_compute_sdk/version.py
  docs/changelog.rst
Labels: no-news-is-good-news

#1828 Update Parsl and Jinja
  changelog.d/20250320_223511_kevin_update_parsl.rst
  compute_endpoint/setup.py
Labels: quick-review

#1830 Request refresh tokens when initializing GlobusApp
  changelog.d/20250325_120334_LeiGlobus_refresh_token_request_sc_40211.rst
  compute_sdk/globus_compute_sdk/sdk/auth/globus_app.py
  compute_sdk/tests/unit/auth/test_globus_app.py
  docs/changelog.rst
Labels: quick-review

#1834 Bump versions and update changelog for v3.4.0 release
  changelog.d/20250305_205605_kevin_v3_function_registration.rst
  changelog.d/20250320_135249_chris_executor_serializer.rst
  changelog.d/20250320_223511_kevin_update_parsl.rst
  changelog.d/20250321_103905_yadudoc1729_shellfunc_name.rst
  compute_endpoint/globus_compute_endpoint/version.py
  compute_endpoint/setup.py
  compute_sdk/globus_compute_sdk/sdk/auth/globus_app.py
  compute_sdk/globus_compute_sdk/version.py
  compute_sdk/tests/unit/auth/test_globus_app.py
  docs/changelog.rst
Labels: no-news-is-good-news, quick-review

#1833 Ensure test prerequisite
  compute_endpoint/tests/integration/test_rabbit_mq/test_task_q.py
Labels: no-news-is-good-news, quick-review

#1835 Fix semantics of wildcard documentation
  docs/endpoints/endpoints.rst
Labels: no-news-is-good-news, quick-review
