Repository globus/globus-compute, pull requests merged in 2025-02, with the labels that each got.

#1787 Add section to SDK docs for GlobusApps
  docs/sdk.rst
Labels: no-news-is-good-news

#1788 Format class names and links in documentation
  docs/sdk.rst
Labels: no-news-is-good-news, quick-review

#1786 Refactor the Endpoint unit tests
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
  compute_endpoint/tests/unit/test_endpoint_unit.py
Labels: no-news-is-good-news

#1792 Remove obsolete upgrade command
  changelog.d/20250206_125215_kevin_remove_obsolete_funcx_upgrade_code.rst
  compute_endpoint/globus_compute_endpoint/cli.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint.py
Labels: quick-review

#1793 Complete overlooked refactor item
  compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
  compute_endpoint/tests/integration/endpoint/executors/mock_executors.py
Labels: no-news-is-good-news, quick-review

#1790 MEP passes identity information to UEP
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
  compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
  compute_endpoint/tests/unit/test_endpoint_unit.py
  compute_endpoint/tests/unit/test_endpointmanager_unit.py
Labels: no-news-is-good-news

#1794 Deprecate executors (list of len() == 1)
  compute_endpoint/globus_compute_endpoint/endpoint/config/config.py
  compute_endpoint/globus_compute_endpoint/endpoint/config/model.py
  compute_endpoint/globus_compute_endpoint/endpoint/config/utils.py
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
  compute_endpoint/globus_compute_endpoint/endpoint/interchange.py
  compute_endpoint/globus_compute_endpoint/endpoint/taskqueue.py
  compute_endpoint/globus_compute_endpoint/engines/process_pool.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint_manager.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_interchange.py
  compute_endpoint/tests/unit/conftest.py
  compute_endpoint/tests/unit/test_endpoint_config.py
  compute_endpoint/tests/unit/test_endpoint_unit.py
  compute_endpoint/tests/unit/test_endpointinterchange.py
  compute_endpoint/tests/unit/test_engines.py
  docs/endpoints/config_reference.rst
Labels: no-news-is-good-news

#1795 Don't leave GCE threads running
  compute_endpoint/tests/integration/endpoint/endpoint/test_interchange.py
  compute_endpoint/tests/integration/endpoint/executors/test_gcengine_retries.py
  compute_endpoint/tests/unit/test_boot_persistence.py
  compute_endpoint/tests/unit/test_cli_behavior.py
  compute_endpoint/tests/unit/test_endpoint_config.py
  compute_endpoint/tests/unit/test_endpoint_unit.py
  compute_endpoint/tests/unit/test_engines.py
  compute_endpoint/tests/unit/test_gce_container.py
  compute_endpoint/tests/unit/test_working_dir.py
Labels: no-news-is-good-news

#1789 Adding an example configuration for Stampede3@TACC
  docs/_static/images/stampede3.jpg
  docs/endpoints/configs/stampede3.yaml
  docs/endpoints/endpoint_examples.rst
Labels: no-news-is-good-news, quick-review

#1798 Update engine status method docstrings
  compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
Labels: no-news-is-good-news, quick-review

#1799 Add total tasks count to GCEngine status report
  compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
  compute_endpoint/tests/unit/engine/test_globuscompute.py
Labels: no-news-is-good-news, quick-review

#1800 Include python version in endpoint registration
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint_manager.py
  compute_endpoint/tests/unit/test_endpoint_unit.py
  compute_endpoint/tests/unit/test_endpointmanager_unit.py
Labels: no-news-is-good-news, quick-review

#1802 Bump versions for release 3.1.0
  changelog.d/20241209_081322_30907815+rjmello_globus_sdk_compute_client_sc_36127.rst
  changelog.d/20241209_143843_30907815+rjmello_globus_sdk_compute_client_sc_36127.rst
  changelog.d/20250122_104738_yadudoc1729_update_parsl_version_req.rst
  changelog.d/20250127_162749_30907815+rjmello.rst
  changelog.d/20250206_125215_kevin_remove_obsolete_funcx_upgrade_code.rst
  changelog.d/20250207_160227_30907815+rjmello_fix_default_engine.rst
  compute_endpoint/globus_compute_endpoint/version.py
  compute_endpoint/setup.py
  compute_sdk/globus_compute_sdk/version.py
  docs/changelog.rst
Labels: no-news-is-good-news, quick-review

#1804 Bump versions for 3.1.1 hotfix
  compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
  compute_endpoint/globus_compute_endpoint/version.py
  compute_endpoint/setup.py
  compute_endpoint/tests/unit/engine/test_globuscompute.py
  compute_sdk/globus_compute_sdk/version.py
  docs/changelog.rst
Labels: no-news-is-good-news, quick-review

#1805 Update jenkins script for building packages
  compute_endpoint/packaging/JenkinsFile
Labels: no-news-is-good-news, quick-review

#1806 Enforce encryption in high assurance endpoints
  compute_endpoint/globus_compute_endpoint/endpoint/endpoint.py
  compute_endpoint/globus_compute_endpoint/engines/base.py
  compute_endpoint/globus_compute_endpoint/engines/globus_compute.py
  compute_endpoint/globus_compute_endpoint/engines/process_pool.py
  compute_endpoint/globus_compute_endpoint/engines/thread_pool.py
  compute_endpoint/tests/integration/endpoint/endpoint/test_endpoint_manager.py
Labels: no-news-is-good-news

#1809 Minor Perlmutter example update.
  docs/endpoints/configs/perlmutter.yaml
Labels: Documentation, no-news-is-good-news

#1810 Serialization strategy list/map cleanup
  compute_sdk/globus_compute_sdk/serialize/base.py
  compute_sdk/globus_compute_sdk/serialize/concretes.py
  compute_sdk/globus_compute_sdk/serialize/facade.py
Labels: no-news-is-good-news, quick-review

#1813 V3.2.0
  changelog.d/20250205_151005_30907815+rjmello_deprecate_login_manager.rst
  changelog.d/20250218_125140_30907815+rjmello_bump_parsl.rst
  compute_endpoint/globus_compute_endpoint/version.py
  compute_endpoint/setup.py
  compute_sdk/globus_compute_sdk/version.py
  docs/changelog.rst
Labels: no-news-is-good-news, quick-review

#1816 (Re-)Add support for Python 3.13
  .github/workflows/ci.yaml
  changelog.d/20250205_154700_chris_re_python_313.rst
  compute_endpoint/tox.ini
  compute_sdk/tox.ini
Labels: quick-review

#1817 Add python version as an argument to local dev docker compose file
  local_dev/compose.yaml
Labels: no-news-is-good-news, quick-review
